force-app/main/default/objects/COWO_First_HierarchyManage__mdt/COWO_First_HierarchyManage__mdt.object-meta.xml
<CustomObject>
    <label>第一階層管理</label>
</CustomObject>

force-app/main/default/objects/COWO_First_HierarchyManage__mdt/fields/COWO_FirstHierarchyText__c.field-meta.xml
<CustomField>
    <fullName>COWO_FirstHierarchyText__c</fullName>
    <label>第一階層テキスト</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COWO_First_HierarchyManage__mdt/fields/COWO_PriceBook_Name__c.field-meta.xml
<CustomField>
    <fullName>COWO_PriceBook_Name__c</fullName>
    <label>価格表名前</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COWO_First_HierarchyManage__mdt/fields/COWO_SecondHierarchyText__c.field-meta.xml
<CustomField>
    <fullName>COWO_SecondHierarchyText__c</fullName>
    <label>第二階層テキスト</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/COWO_Second_HierarchyManage__mdt/COWO_Second_HierarchyManage__mdt.object-meta.xml
<CustomObject>
    <label>第二階層管理</label>
</CustomObject>

force-app/main/default/objects/COWO_Second_HierarchyManage__mdt/fields/COWO_SecondHierarchyText__c.field-meta.xml
<CustomField>
    <fullName>COWO_SecondHierarchyText__c</fullName>
    <label>第二階層テキスト</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COWO_Second_HierarchyManage__mdt/fields/COWO_ThirdHierarchyText__c.field-meta.xml
<CustomField>
    <fullName>COWO_ThirdHierarchyText__c</fullName>
    <label>第三階層テキスト</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COWO_FrontPurchasePrice__c.field-meta.xml
<CustomField>
    <fullName>COWO_FrontPurchasePrice__c</fullName>
    <label>フロント仕入価格</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COWO_LocalCorporationTC__c.field-meta.xml
<CustomField>
    <fullName>COWO_LocalCorporationTC__c</fullName>
    <label>現法TC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COWO_MC__c.field-meta.xml
<CustomField>
    <fullName>COWO_MC__c</fullName>
    <label>MC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COWO_TC__c.field-meta.xml
<CustomField>
    <fullName>COWO_TC__c</fullName>
    <label>TC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/PartitionPrice__c.field-meta.xml
<CustomField>
    <fullName>PartitionPrice__c</fullName>
    <label>X</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Pricebook2EntryKey__c.field-meta.xml
<CustomField>
    <fullName>Pricebook2EntryKey__c</fullName>
    <description>パーツNO　と　製品略称を　アンダースコア（ _ ）で繋いだものを外部IDとして格納。</description>
    <externalId>true</externalId>
    <label>価格表エントリ キー</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Saiteibaika__c.field-meta.xml
<CustomField>
    <fullName>Saiteibaika__c</fullName>
    <label>最低売価</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/SAWO_FirstHierarchy__c.field-meta.xml
<CustomField>
    <fullName>SAWO_FirstHierarchy__c</fullName>
    <formula>Product2.SAWO_FirstHierarchy__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>第一階層</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/SAWO_SecondHierarchy__c.field-meta.xml
<CustomField>
    <fullName>SAWO_SecondHierarchy__c</fullName>
    <formula>Product2.SAWO_SecondHierarchy__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>第二階層</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/SAWO_ThirdHierarchy__c.field-meta.xml
<CustomField>
    <fullName>SAWO_ThirdHierarchy__c</fullName>
    <formula>Product2.SAWO_ThirdHierarchy__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>第三階層</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Supplier_Amount__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Amount__c</fullName>
    <label>仕入額</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Teika__c.field-meta.xml
<CustomField>
    <fullName>Teika__c</fullName>
    <label>定価</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/b__c.field-meta.xml
<CustomField>
    <fullName>b__c</fullName>
    <inlineHelpText>標準納期</inlineHelpText>
    <label>b</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CountryMode__c.field-meta.xml
<CustomField>
    <fullName>CountryMode__c</fullName>
    <label>国モード</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ItemName__c.field-meta.xml
<CustomField>
    <fullName>ItemName__c</fullName>
    <label>製品名</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Katashiki__c.field-meta.xml
<CustomField>
    <fullName>Katashiki__c</fullName>
    <description>(補足)
型式の接頭辞として、以下の名前が付く場合は、案件製品一括編集画面で自由入力商品を選択した際の選択リストに表示される。

自社部品
HHS
商社品</description>
    <label>型式</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ItemDivision__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>SU9000</fullName>
            </value>
            <value>
                <fullName>SU8240(Regulus)</fullName>
            </value>
            <value>
                <fullName>SU8230(Regulus)</fullName>
            </value>
            <value>
                <fullName>SU8220(Regulus)</fullName>
            </value>
            <value>
                <fullName>SU8100</fullName>
            </value>
            <value>
                <fullName>SU8240</fullName>
            </value>
            <value>
                <fullName>SU8230</fullName>
            </value>
            <value>
                <fullName>SU8220</fullName>
            </value>
            <value>
                <fullName>SU8010</fullName>
            </value>
            <value>
                <fullName>SU5000</fullName>
            </value>
            <value>
                <fullName>SU-70</fullName>
            </value>
            <value>
                <fullName>SU7000</fullName>
            </value>
            <value>
                <fullName>SU3500(5MD)</fullName>
            </value>
            <value>
                <fullName>SU3500(4MD)</fullName>
            </value>
            <value>
                <fullName>S-3700N</fullName>
            </value>
            <value>
                <fullName>SU1510</fullName>
            </value>
            <value>
                <fullName>FlexSEM1000</fullName>
            </value>
            <value>
                <fullName>FlexSEM1000Ⅱ</fullName>
            </value>
            <value>
                <fullName>SU3900</fullName>
            </value>
            <value>
                <fullName>SU3800</fullName>
            </value>
            <value>
                <fullName>IM4000</fullName>
            </value>
            <value>
                <fullName>冷却付 IM4000</fullName>
            </value>
            <value>
                <fullName>IM4000PLUS</fullName>
            </value>
            <value>
                <fullName>冷却付 IM4000PLUS</fullName>
            </value>
            <value>
                <fullName>IM5000</fullName>
            </value>
            <value>
                <fullName>冷却付 IM5000</fullName>
            </value>
            <value>
                <fullName>MC1000</fullName>
            </value>
            <value>
                <fullName>TM3030</fullName>
            </value>
            <value>
                <fullName>TM3030Plus</fullName>
            </value>
            <value>
                <fullName>TM4000</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/MC__c.field-meta.xml
<CustomField>
    <fullName>MC__c</fullName>
    <inlineHelpText>原価</inlineHelpText>
    <label>MC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/PartitionPrice__c.field-meta.xml
<CustomField>
    <fullName>PartitionPrice__c</fullName>
    <label>仕切り価格</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/PartsNo__c.field-meta.xml
<CustomField>
    <fullName>PartsNo__c</fullName>
    <label>パーツ No. 見積 No.</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Q__c.field-meta.xml
<CustomField>
    <fullName>Q__c</fullName>
    <inlineHelpText>仕切り価格</inlineHelpText>
    <label>Q</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SAWO_FirstHierarchy__c.field-meta.xml
<CustomField>
    <fullName>SAWO_FirstHierarchy__c</fullName>
    <label>第一階層</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SAWO_NoDiscountFlg__c.field-meta.xml
<CustomField>
    <fullName>SAWO_NoDiscountFlg__c</fullName>
    <defaultValue>false</defaultValue>
    <label>値引対象外フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SAWO_OrderNnumber__c.field-meta.xml
<CustomField>
    <fullName>SAWO_OrderNnumber__c</fullName>
    <label>受注項番</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SAWO_SalesUnit__c.field-meta.xml
<CustomField>
    <fullName>SAWO_SalesUnit__c</fullName>
    <label>販売単位</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>%</fullName>
            </value>
            <value>
                <fullName>%O</fullName>
            </value>
            <value>
                <fullName>°F</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>22S</fullName>
            </value>
            <value>
                <fullName>33</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>ACR</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>BAG</fullName>
            </value>
            <value>
                <fullName>BAR</fullName>
            </value>
            <value>
                <fullName>bbl</fullName>
            </value>
            <value>
                <fullName>bft</fullName>
            </value>
            <value>
                <fullName>bgl</fullName>
            </value>
            <value>
                <fullName>BQK</fullName>
            </value>
            <value>
                <fullName>Bqm</fullName>
            </value>
            <value>
                <fullName>bsc</fullName>
            </value>
            <value>
                <fullName>btl</fullName>
            </value>
            <value>
                <fullName>BTU</fullName>
            </value>
            <value>
                <fullName>BYr</fullName>
            </value>
            <value>
                <fullName>C3S</fullName>
            </value>
            <value>
                <fullName>CAN</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CCM</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CD3</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/SAWO_SecondHierarchy__c.field-meta.xml
<CustomField>
    <fullName>SAWO_SecondHierarchy__c</fullName>
    <label>第二階層</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SAWO_ThirdHierarchy__c.field-meta.xml
<CustomField>
    <fullName>SAWO_ThirdHierarchy__c</fullName>
    <label>第三階層</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/StructureSortNo__c.field-meta.xml
<CustomField>
    <fullName>StructureSortNo__c</fullName>
    <label>構成順</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SupplierName__c.field-meta.xml
<CustomField>
    <fullName>SupplierName__c</fullName>
    <label>仕入先</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/TC__c.field-meta.xml
<CustomField>
    <fullName>TC__c</fullName>
    <inlineHelpText>トータルコスト</inlineHelpText>
    <label>TC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/QuoteLineItemSearchProductController.cls
public with sharing class QuoteLineItemSearchProductController {
    
    public static List<String> TARGET_FIELDS = new List<String>{
          'Product2.Id'
        , 'Product2.CountryMode__c'
        , 'Product2.Katashiki__c'
        , 'Product2.Name'
        , 'Product2.ProductCode'
        , 'Product2.SupplierName__c'
        , 'Product2.PartsNo__c'
        , 'Product2.Description'
        , 'Product2.b__c'
        , 'Product2.PartitionPrice__c'
        , 'Product2.Q__c'
        , 'Product2.TC__c'
        , 'Product2.MC__c'
        , 'Product2.StructureSortNo__c'
        , 'Product2.CurrencyIsoCode'
        , 'UnitPrice'
        , 'PartitionPrice__c'
        , 'Pricebook2EntryKey__c'
        , 'Supplier_Amount__c'
        , 'Saiteibaika__c'
        , 'Teika__c'
        , 'COWO_LocalCorporationTC__c'
        , 'COWO_FrontPurchasePrice__c'
        , 'COWO_TC__c'
        , 'COWO_MC__c'
        , 'Product2.SAWO_OrderNnumber__c'
        , 'Product2.SAWO_SalesUnit__c'
        , 'Product2.SAWO_NoDiscountFlg__c'
    };

    public static SearchCondition condition{ get;set; } 
    
    /**
     * 画面初期処理
     * @param なし
     * @return 結果
     */
    @AuraEnabled
    public static String init(String quoteId,String pricebook2Id){

        Quote quote = [SELECT CurrencyIsoCode, Pricebook2Id FROM Quote WHERE Id = :quoteId];
        Pricebook2 pb2 = [select name from Pricebook2 where id =: pricebook2Id];
        List<COWO_First_HierarchyManage__mdt> firstHierarchyMDTList = [select COWO_FirstHierarchyText__c,COWO_SecondHierarchyText__c from COWO_First_HierarchyManage__mdt where COWO_PriceBook_Name__c =: pb2.name];
        List<COWO_Second_HierarchyManage__mdt> secondHierarchyMDTList = [select COWO_ThirdHierarchyText__c,COWO_SecondHierarchyText__c from COWO_Second_HierarchyManage__mdt where COWO_PriceBook_Name__c =: pb2.name];
        Set<String> firstHierarchyMDTSet = new Set<String>();
        //Set<String> secondHierarchyMDTSet =new Set<String>();
        //Map<String,List<String>> secondHierarchyOptionMap = new Map<String,List<String>>();
        //Map<String,List<String>> thirdHierarchyOptionMap = new Map<String,List<String>>();
        Map<String,List<SerializableSelectOption>> secondHierarchyOptionMap = new Map<String,List<SerializableSelectOption>>();
        Map<String,List<SerializableSelectOption>> thirdHierarchyOptionMap = new Map<String,List<SerializableSelectOption>>();
        if(firstHierarchyMDTList.size() > 0){
            for(COWO_First_HierarchyManage__mdt firstHierarchyMDT : firstHierarchyMDTList){
                firstHierarchyMDTSet.add(firstHierarchyMDT.COWO_FirstHierarchyText__c);
                if(firstHierarchyMDT.COWO_SecondHierarchyText__c != null){
                    List<String> secondHierarchyList = firstHierarchyMDT.COWO_SecondHierarchyText__c.split(',');
                    Set<String> secondHierarchySet = new Set<String>();
                    for(String secondHierarchy : secondHierarchyList){
                        secondHierarchySet.add(secondHierarchy);
                    }
                    List<SerializableSelectOption> secondHierarchySelectOptionList = getSalutationPicklist(secondHierarchySet);
                    secondHierarchyOptionMap.put(firstHierarchyMDT.COWO_FirstHierarchyText__c,secondHierarchySelectOptionList);
                }
            }
            if(secondHierarchyMDTList.size() > 0){
                for(COWO_Second_HierarchyManage__mdt secondHierarchyMDT : secondHierarchyMDTList){
                    //secondHierarchyMDTSet.add(secondHierarchyMDT.COWO_SecondHierarchyText__c);
                    if(secondHierarchyMDT.COWO_ThirdHierarchyText__c != null){
                        List<String> thirdHierarchyList = secondHierarchyMDT.COWO_ThirdHierarchyText__c.split(',');
                        Set<String> thirdHierarchySet = new Set<String>();
                        for(String thirdHierarchy : thirdHierarchyList){
                            thirdHierarchySet.add(thirdHierarchy);
                        }
                        List<SerializableSelectOption> thirdHierarchySelectOptionList = getSalutationPicklist(thirdHierarchySet);
                        thirdHierarchyOptionMap.put(secondHierarchyMDT.COWO_SecondHierarchyText__c,thirdHierarchySelectOptionList);
                    }
                }
            }

            List<SerializableSelectOption> firstHierarchyOptionsList = getSalutationPicklist(firstHierarchyMDTSet);
            List<SerializableSelectOption>  secondHierarchyOptionsList = new List<SerializableSelectOption>();//getSalutationPicklist(secondHierarchySet);
            List<SerializableSelectOption>  thirdHierarchyOptionsList = new List<SerializableSelectOption>();//getSalutationPicklist(thirdHierarchySet);
            System.debug('firstHierarchyOptionsList' + firstHierarchyOptionsList);
            JSONGenerator gen = JSON.createGenerator(true);
            gen.writeStartObject();
            gen.writeNumberField('returnCode', 0); // 正常終了
            //gen.writeObjectField('Katashiki__c', selectOptionsList);
            gen.writeObjectField('firstHierarchyOptions', firstHierarchyOptionsList);
            gen.writeObjectField('secondHierarchyOptions', secondHierarchyOptionsList);
            gen.writeObjectField('thirdHierarchyOptions', thirdHierarchyOptionsList);
            gen.writeObjectField('secondHierarchyMap', secondHierarchyOptionMap);
            gen.writeObjectField('thirdHierarchyMap', thirdHierarchyOptionMap);
            gen.writeStringField('currencyIsoCode', quote.currencyIsoCode);
            gen.writeEndObject();

            
            // Get the JSON string.
            String JSONString = gen.getAsString();

            return JSONString;
        }else{
            List<pricebookentry> pricebookentryList = [select SAWO_FirstHierarchy__c, SAWO_SecondHierarchy__c,SAWO_ThirdHierarchy__c from pricebookentry  where Pricebook2Id =: pricebook2Id order by SAWO_FirstHierarchy__c, SAWO_SecondHierarchy__c,SAWO_ThirdHierarchy__c]; 
            Set<String> firstHierarchySet = new Set<String>();
            Set<String> secondHierarchySet = new Set<String>();
            Set<String> thirdHierarchySet = new Set<String>();
            if(pricebookentryList != null){
                for(pricebookentry p : pricebookentryList){
                    if(p.SAWO_FirstHierarchy__c != null){
                        firstHierarchySet.add(p.SAWO_FirstHierarchy__c);
                    }
                    if(p.SAWO_SecondHierarchy__c != null){
                        secondHierarchySet.add(p.SAWO_SecondHierarchy__c);
                    }
                    if(p.SAWO_ThirdHierarchy__c != null){
                        thirdHierarchySet.add(p.SAWO_ThirdHierarchy__c);
                    }
                }
            }
            Boolean isFirstHierarchyExist = false;
            Boolean isSecondHierarchyExist = false;
            Boolean isThirdHierarchyExist = false;
            if(firstHierarchySet.size() > 0){
                isFirstHierarchyExist = true;
            }
            if(secondHierarchySet.size() > 0){
                isSecondHierarchyExist = true;
            }
            if(thirdHierarchySet.size() > 0){
                isThirdHierarchyExist = true;
            }
            system.debug(firstHierarchySet);
            system.debug(secondHierarchySet);
            system.debug(thirdHierarchySet);
    
            List<SerializableSelectOption> firstHierarchyOptionsList = getSalutationPicklist(firstHierarchySet);
            List<SerializableSelectOption>  secondHierarchyOptionsList = getSalutationPicklist(secondHierarchySet);
            List<SerializableSelectOption>  thirdHierarchyOptionsList = getSalutationPicklist(thirdHierarchySet);

            JSONGenerator gen = JSON.createGenerator(true);
            gen.writeStartObject();
            gen.writeNumberField('returnCode', 0); // 正常終了
            gen.writeObjectField('firstHierarchyOptions', firstHierarchyOptionsList);
            gen.writeObjectField('secondHierarchyOptions', secondHierarchyOptionsList);
            gen.writeObjectField('thirdHierarchyOptions', thirdHierarchyOptionsList);
            gen.writeBooleanField('isFirstHierarchyExist',isFirstHierarchyExist);
            gen.writeBooleanField('isSecondHierarchyExist',isSecondHierarchyExist);
            gen.writeBooleanField('isThirdHierarchyExist',isThirdHierarchyExist);
            gen.writeStringField('currencyIsoCode', quote.currencyIsoCode);
            gen.writeEndObject();
    
            
            // Get the JSON string.
            String JSONString = gen.getAsString();
    
            return JSONString;

        }
    }
    
    /**
     * 画面入力条件により、商品を検索する
     * @param countryMode__c:検索条件 国コード
     * @param katashiki__c:検索条件 型式
     * @param productCalledName:検索条件 商品略称
     * @param structureSortNo__c:検索条件 構成順
     * @param itemName:検索条件 商品名
     * @param partsNo:検索条件 パーツNo.
     * @return 検索結果
     */
    @AuraEnabled
    public static String searchProduct(String quoteId,
                                       String pricebook2Id, 
                                       String firstLayer, 
                                       String secondLayer, 
                                       String thaadLayer, 
                                       String product2_Name, 
                                       String partsNo,
                                       Boolean isPSGHHTUser){

        // // 異常終了時のロールバックポイント
        // Savepoint sp = Database.setSavepoint();
        system.debug(quoteId);
		Quote quote = [SELECT CurrencyIsoCode FROM Quote WHERE Id = :quoteId];
        system.debug('quote.CurrencyIsoCode' + quote.CurrencyIsoCode);
        String currencyIsoCode = quote.CurrencyIsoCode;                               
                                           
        // try{
            // 検索条件を設定する
            condition = new SearchCondition(pricebook2Id, firstLayer, secondLayer, thaadLayer,  product2_Name, partsNo, currencyIsoCode);

            // 件数チェック
            Integer count = doCount();
            System.debug('★★★★★ count ★★★★★' + count);
            // Integer count = [select count() 
            //                  from Product2
            //                  where CountryMode__c =: countryMode 
            //                  and Katashiki__c =: katashiki
            //                  and StructureSortNo__c =: structureSortNo];


            // JSONGenerator gen = JSON.createGenerator(true);
            // gen.writeStartObject();
            // gen.writeNumberField('returnCode', 9); // 警告終了
            // gen.writeObjectField('returnMsg', condition);
            // gen.writeEndObject();
            
            // // Get the JSON string.
            // String jsonString = gen.getAsString();
            // return jsonString;
        
            // ０件の場合
            if (count == 0){
                String resultString = doZeroEnd();
                return resultString;
            }

            // 検索を行う
            List<PricebookEntry> pricebookEntryList = doSearch();
            List<QuoteLineItemSearchProducts> searchProducts = new List<QuoteLineItemSearchProducts> ();
            for (PricebookEntry pricebookEntry : pricebookEntryList) {
                QuoteLineItemSearchProducts searchProduct = new QuoteLineItemSearchProducts();
                searchProduct.product2_Id = pricebookEntry.Product2.Id;
                searchProduct.product2_CountryMode = pricebookEntry.Product2.CountryMode__c;
                searchProduct.product2_Katashiki = pricebookEntry.Product2.Katashiki__c;
                searchProduct.product2_ItemName = pricebookEntry.Product2.Name;
                searchProduct.product2_ProductCode = pricebookEntry.Product2.ProductCode;
                searchProduct.product2_SupplierName = pricebookEntry.Product2.SupplierName__c;
                searchProduct.product2_PartsNo = pricebookEntry.Product2.PartsNo__c;
                searchProduct.product2_Description = pricebookEntry.Product2.Description;
                searchProduct.product2_b = pricebookEntry.Product2.b__c;
                searchProduct.product2_PartitionPrice = pricebookEntry.Product2.PartitionPrice__c;
                searchProduct.product2_Q = pricebookEntry.Product2.Q__c;
                searchProduct.product2_TC = pricebookEntry.Product2.TC__c;
                searchProduct.product2_MC = pricebookEntry.Product2.MC__c;
                searchProduct.product2_StructureSortNo = pricebookEntry.Product2.StructureSortNo__c;
                searchProduct.product2_CurrencyIsoCode = pricebookEntry.Product2.CurrencyIsoCode;
                searchProduct.unitPrice = pricebookEntry.UnitPrice;
                searchProduct.partitionPrice = pricebookEntry.PartitionPrice__c;
                searchProduct.pricebook2EntryKey = pricebookEntry.Pricebook2EntryKey__c;
                searchProduct.supplier_Amount = pricebookEntry.Supplier_Amount__c;
                searchProduct.saiteibaika = pricebookEntry.Saiteibaika__c;
                searchProduct.teika = pricebookEntry.Teika__c;
                searchProduct.localCorporationTC = pricebookEntry.COWO_LocalCorporationTC__c;
                searchProduct.frontPurchasePrice = pricebookEntry.COWO_FrontPurchasePrice__c;
                searchProduct.pricebookentry_TC = pricebookEntry.COWO_TC__c;
                searchProduct.pricebookentry_MC = pricebookEntry.COWO_MC__c;
                searchProduct.subtotal = pricebookEntry.UnitPrice != null ? pricebookEntry.UnitPrice : 0;
                searchProduct.display_TC = isPSGHHTUser ? pricebookEntry.Product2.TC__c : 0;
                searchProduct.display_MC = isPSGHHTUser ? pricebookEntry.Product2.MC__c : 0;
                searchProduct.product2_OrderNumber = pricebookEntry.Product2.SAWO_OrderNnumber__c;
                searchProduct.product2_SalesUnit = pricebookEntry.Product2.SAWO_SalesUnit__c;
                searchProduct.product2_NoDiscountFlg = pricebookEntry.Product2.SAWO_NoDiscountFlg__c;
                searchProducts.add(searchProduct);
            }
            // List<Product2> product2s = [select 
            //                                 Id, 
            //                                 CountryMode__c,
            //                                 Katashiki__c,
            //                                 ItemName__c,
            //                                 ProductCode,
            //                                 SupplierName__c,
            //                                 PartsNo__c,
            //                                 Description,
            //                                 b__c,
            //                                 PartitionPrice__c,
            //                                 Q__c,
            //                                 TC__c,
            //                                 MC__c,
            //                                 StructureSortNo__c
            //                             from Product2
            //                             where CountryMode__c =: countryMode 
            //                             and Katashiki__c =: katashiki
            //                             and StructureSortNo__c =: structureSortNo
            //                             limit 200];

            // 正常終了の場合
            String resultString = doNormalEnd(searchProducts, count);
            return resultString;
            
        // } catch (Exception e){

        //     // 異常終了する場合、ロールバックする
        //     Database.rollback(sp);
            
        //     JSONGenerator gen = JSON.createGenerator(true);
        //     gen.writeStartObject();
        //     gen.writeNumberField('returnCode', 9); // 異常終了
        //     gen.writeObjectField('returnMsg', e.getMessage());
        //     gen.writeEndObject();
            
        //     // Get the JSON string.
        //     String jsonString = gen.getAsString();
        //     return jsonString;
        // }
    }

    /**
     * ０件の場合
     * @param なし
     * @return 処理結果
     */
    private static String doZeroEnd(){
        System.debug('★★★★★ 正常終了処理 start ★★★★★');

        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        gen.writeNumberField('returnCode', 6); // 警告終了
        gen.writeObjectField('returnMsg', System.Label.Product2Search_NoDataFetch);
        gen.writeObjectField('count', 0);
        gen.writeEndObject();
        
        // Get the JSON string.
        String jsonString = gen.getAsString();
        
        System.debug('★★★★★ jsonString ★★★★★' + jsonString);
        
        System.debug('★★★★★ 正常終了処理 end ★★★★★');

        return jsonString;
    }

    /**
     * 正常終了処理
     * @param quoteLineItemSearchProductList:データリスト
     * @return 処理結果
     */
    private static String doNormalEnd(List<QuoteLineItemSearchProducts> quoteLineItemSearchProductList, Integer count){
        System.debug('★★★★★ 正常終了処理 start ★★★★★');

        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        gen.writeNumberField('returnCode', 0); // 正常終了
        if (count > 200){
            // 200件以上合致する場合、警告メッセージを表示する
            gen.writeObjectField('returnMsg', System.Label.Product2Search_FetchDataMoreThan200);
        } else{
            gen.writeObjectField('returnMsg', System.Label.Product2Search_NormalEnd);
        }
        gen.writeObjectField('data', quoteLineItemSearchProductList);
        gen.writeNumberField('count', count);
        gen.writeEndObject();
        
        // Get the JSON string.
        String jsonString = gen.getAsString();
        
        System.debug('★★★★★ jsonString ★★★★★' + jsonString);
        
        System.debug('★★★★★ 正常終了処理 end ★★★★★');

        return jsonString;
    }

    public static Map<String, String> convPicklistValues(String objectName, String fieldName) {
        Map<String, String> values = new Map<String, String>{};

        List<Schema.DescribeSobjectResult> resultList = Schema.describeSObjects(new List<String>{objectName});
        
        for(Schema.DescribeSobjectResult res : resultList) {
            for (Schema.PicklistEntry entry : res.fields.getMap().get(fieldName).getDescribe().getPicklistValues()) {
                if (entry.isActive()) {
                    values.put(entry.getValue(), entry.getLabel());
                }
            }
        }

        return values;
    }

    public static List<SerializableSelectOption> getSalutationPicklist(SerializableSelectOption selectOption, String objectName, String fieldName) {
        List<SerializableSelectOption> selectOptionsList = new List<SerializableSelectOption>();
        if(selectOption != null){
            selectOptionsList.add(selectOption);
        }

        Map<String, String> salutationValueLabels = convPicklistValues(objectName, fieldName);
        for (String value : salutationValueLabels.keySet()) {
            selectOptionsList.add(new SerializableSelectOption(value, salutationValueLabels.get(value)));
        }

        return selectOptionsList;
    }

    public static List<SerializableSelectOption> getSalutationPicklist(Set<String> targetFieldSet) {
        List<SerializableSelectOption> selectOptionsList = new List<SerializableSelectOption>();
        selectOptionsList.add(new SerializableSelectOption('--',''));
        for (String value : targetFieldSet) {
            selectOptionsList.add(new SerializableSelectOption(value, value));
        }
        return selectOptionsList;
    }
    
    public static Integer doCount(){
        String soqlCountQuery = condition.getSoqlCountQuery();
        System.debug('★★★★★ soqlCountQuery ★★★★★' + soqlCountQuery);
        return database.countQuery(soqlCountQuery);
    }
    
    public static List<SObject> doSearch(){
        String soqlQuery = condition.getSoqlQuery();
        System.debug('★★★★★ soqlQuery ★★★★★' + soqlQuery);
        return database.query(soqlQuery);
    }

    public Class SearchCondition {

        public PricebookEntry obj {get;set;} 

        public String sortkey { get;set; }

        public String order { get;set; }

        private String pricebook2Id;

        //private String countryMode;

        // private String katashiki;

        // private String productCalledName;

        // private String structureSortNo;

        private String firstLayer;

        private String secondLayer;

        private String thaadLayer;

        private String product2_Name;

        private String partsNo;

        private String currencyIsoCode;

        public SearchCondition(String pricebook2Id,
                               String firstLayer, 
                               String secondLayer, 
                               String thaadLayer, 
                               String product2_Name, 
                               String partsNo,
                               String currencyIsoCode){
            this.pricebook2Id = pricebook2Id;
            this.firstLayer = firstLayer;
            this.secondLayer = secondLayer;
            this.thaadLayer = thaadLayer;
            this.product2_Name = product2_Name.trim();
            this.partsNo = partsNo.trim();
            this.currencyIsoCode = currencyIsoCode;                       

            this.obj = new PricebookEntry();
            sortkey = 'Product2.StructureSortNo__c';
            order = 'ASC';
        }
  
        public String getSoqlCountQuery(){
            List<String> param = new String[]{ getWhere() };
            return String.format('SELECT COUNT() FROM PricebookEntry {0}', param);
        }
  
        public String getSoqlQuery(){
            List<String> param = new String[]{ getFieldList(), getWhere(), getOrder() };
            return String.format('SELECT {0} FROM PricebookEntry {1}{2} LIMIT 200', param);
        }
        
        private String getFieldList(){
            return String.join(TARGET_FIELDS, ',');
        }

        private String getWhere(){
            List<String> param = new String[]{ };
            // String ani = ApexPages.currentPage().getParameters().get('ANI');
            
            // String queryAni = escape(ani);
                
            // param.add('Phone like \'%' + queryAni + '\'');
            // param.add('TelNo1__c like \'%' + queryAni + '\'');
            // param.add('TelNo2__c like \'%' + queryAni + '\'');
			System.debug('★' + pricebook2Id);
            // 検索条件を設定する
            String pricebook2Id = escape(pricebook2Id);
            // String countryMode = escape(countryMode);
            // String katashiki = escape(katashiki);
            // String productCalledName = escape(productCalledName);
            // String structureSortNo = escape(structureSortNo);
            String firstLayer = escape(firstLayer);
            String secondLayer = escape(secondLayer);
            String thaadLayer = escape(thaadLayer);
            String product2_Name = escape(product2_Name);
            String partsNo = escape(partsNo);
			String currencyIsoCode = escape(currencyIsoCode);
            
            if(String.isNotBlank(pricebook2Id)){
                param.add('Pricebook2Id = \'' + pricebook2Id + '\'');
            }
            // if(String.isNotBlank(countryMode)){
            //     param.add('Product2.CountryMode__c = \'' + countryMode + '\'');
            // }
            // if(String.isNotBlank(katashiki)){
            //     param.add('Product2.Katashiki__c = \'' + katashiki + '\'');
            // }
            // if(String.isNotBlank(productCalledName)){
            //     param.add('Product2.ProductCalledName__c like \'%' + productCalledName + '%\'');
            // }
            // if(String.isNotBlank(structureSortNo)){
            //     param.add('Product2.StructureSortNo__c like \'%' + structureSortNo + '%\'');
            // }
            if(String.isNotBlank(firstLayer)){
                param.add('Product2.SAWO_FirstHierarchy__c = \'' + firstLayer + '\'');
            }
            if(String.isNotBlank(secondLayer)){
                param.add('Product2.SAWO_SecondHierarchy__c = \'' + secondLayer + '\'');
            }
            if(String.isNotBlank(thaadLayer)){
                param.add('Product2.SAWO_ThirdHierarchy__c = \'' + thaadLayer + '\'');
            }
            if(String.isNotBlank(product2_Name)){
                param.add('Product2.Name like \'%' + product2_Name + '%\'');
            }
            if(String.isNotBlank(partsNo)){
                param.add('Product2.PartsNo__c like \'%' + partsNo + '%\'');
            }
            if(String.isNotBlank(currencyIsoCode)){
                param.add('Product2.currencyIsoCode = \'' + currencyIsoCode + '\'');
            }
            if(String.isNotBlank(currencyIsoCode)){
                param.add('currencyIsoCode = \'' + currencyIsoCode + '\'');
            }
            param.add('isActive = true ');

            if(param.isEmpty()){
                return '';
            }
            return 'WHERE ' + String.join(param, ' AND ');
        }

        private String getOrder(){
            List<String> paramList = new String[]{ sortkey, order };
            return String.format('ORDER BY {0} {1}', paramList);
        }

        // public void setOrderReverse(){
        //     if(this.order == 'DESC'){
        //         this.order = 'ASC';
        //     }else{
        //         this.order = 'DESC';
        //     }
        // }

        // public String sortOrderToString(){
        //     if(this.order == 'DESC'){
        //         return '↓';
        //     }
        //     return '↑';
        // }

        private String escape(String str){
            String retStr = String.escapeSingleQuotes(str);
            retStr = retStr.replace('%', '\\%');
            // retStr = retStr.replace('_', '\\_');
            return retStr;
        }
    }

    // public String getSortKey(){
    //     return this.condition.sortkey;
    // }

    // public String getSortOrder(){
    //     return this.condition.sortOrderToString();
    // }

    public class SerializableSelectOption {

        public String label {get; set;}
        public String value {get; set;}

        public SerializableSelectOption(SelectOption so) {
            this.label = so.getLabel();
            this.value = so.getValue();
        }

        public SerializableSelectOption(PicklistEntry pe) {
            this.label = pe.getLabel();
            this.value = pe.getValue();
        }

        public SerializableSelectOption(String label, String value) {
            this.label = label;
            this.value = value;
        }
    }

    public class QuoteLineItemSearchProducts {
        public String product2_Id {get;set;}
        public String product2_CountryMode {get;set;}
        public String product2_Katashiki {get;set;}
        public String product2_ItemName {get;set;}
        public String product2_ProductCode {get;set;}
        public String product2_SupplierName {get;set;}
        public String product2_PartsNo {get;set;}
        public String product2_Description {get;set;}
        public Decimal product2_b {get;set;}
        public Decimal product2_PartitionPrice {get;set;}
        public Decimal product2_Q {get;set;}
        public Decimal product2_TC {get;set;}
        public Decimal product2_MC {get;set;}
        public String product2_StructureSortNo {get;set;}
        public String product2_CurrencyIsoCode {get;set;}
        public Decimal unitPrice {get;set;}
        public Decimal partitionPrice {get;set;}
        public String pricebook2EntryKey {get;set;}
        public Decimal supplier_Amount {get;set;}
        public Decimal saiteibaika {get;set;}
        public Decimal teika {get;set;}
        public Decimal localCorporationTC {get;set;}
        public Decimal frontPurchasePrice {get;set;}
        public Decimal pricebookentry_TC {get;set;}
        public Decimal pricebookentry_MC {get;set;}
        public Decimal subtotal{get;set;}
        public Decimal display_TC {get;set;}
        public Decimal display_MC {get;set;}
        public Decimal product2_OrderNumber {get;set;}
        public String product2_SalesUnit {get;set;}
        public Boolean product2_NoDiscountFlg {get;set;}
    }
}