force-app/main/default/objects/QuoteLineItem/fields/COWO_Currency__c.field-meta.xml
<CustomField>
    <fullName>COWO_Currency__c</fullName>
    <description>取引先マスタの項目値</description>
    <label>通貨</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/COWO_DetailCategory__c.field-meta.xml
<CustomField>
    <fullName>COWO_DetailCategory__c</fullName>
    <description>SAPの明細カテゴリ</description>
    <label>明細カテゴリ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Z110</fullName>
                <label>Z110:直送</label>
            </value>
            <value>
                <fullName>Z100</fullName>
                <label>Z100:在庫引当</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/COWO_DetailCategory_MTE__c.field-meta.xml
<CustomField>
    <fullName>COWO_DetailCategory_MTE__c</fullName>
    <label>Item Category (MTE)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CB1</fullName>
                <label>CB1:Drop ship w Not.</label>
            </value>
            <value>
                <fullName>CB2</fullName>
                <label>CB:2:Drop ship w/out Not.</label>
            </value>
            <value>
                <fullName>TAN</fullName>
                <default>true</default>
                <label>TAN:Distribution</label>
            </value>
            <value>
                <fullName>DB1</fullName>
                <label>DB1:DwnPmt Drop Ship w Not.</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/COWO_MaterialGroup1__c.field-meta.xml
<CustomField>
    <fullName>COWO_MaterialGroup1__c</fullName>
    <description>S4連携項目</description>
    <label>品目グループ1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E</fullName>
                <label>E:設計手配</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>C:自動手配</label>
            </value>
            <value>
                <fullName>W</fullName>
                <label>W:WBS手配</label>
            </value>
            <value>
                <fullName>Z01</fullName>
                <label>Z01:特殊鋼</label>
            </value>
            <value>
                <fullName>Z02</fullName>
                <label>Z02:普通鋼・非鉄原料・非鉄製品</label>
            </value>
            <value>
                <fullName>Z03</fullName>
                <label>Z03:機能部品・樹脂原料</label>
            </value>
            <value>
                <fullName>Z04</fullName>
                <label>Z04:半導体・液晶・液晶部材</label>
            </value>
            <value>
                <fullName>001</fullName>
                <label>001:電子</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>002:光学</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>003:SEM</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>004:TEM</label>
            </value>
            <value>
                <fullName>005</fullName>
                <label>005:バイオ</label>
            </value>
            <value>
                <fullName>006</fullName>
                <label>006:医用</label>
            </value>
            <value>
                <fullName>007</fullName>
                <label>007:評価新事業</label>
            </value>
            <value>
                <fullName>008</fullName>
                <label>008:ゲート</label>
            </value>
            <value>
                <fullName>009</fullName>
                <label>009:アッシャー</label>
            </value>
            <value>
                <fullName>010</fullName>
                <label>010:プロセス部品</label>
            </value>
            <value>
                <fullName>011</fullName>
                <label>011:プロセス改造</label>
            </value>
            <value>
                <fullName>012</fullName>
                <label>012:分析（HHS）/（HHA）</label>
            </value>
            <value>
                <fullName>013</fullName>
                <label>013:HFS</label>
            </value>
            <value>
                <fullName>014</fullName>
                <label>014:HSL</label>
            </value>
            <value>
                <fullName>015</fullName>
                <label>015:HMS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/COWO_PlantCode__c.field-meta.xml
<CustomField>
    <fullName>COWO_PlantCode__c</fullName>
    <description>S4連携用項目</description>
    <label>プラント (STE)</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/COWO_PlantCode_MTE__c.field-meta.xml
<CustomField>
    <fullName>COWO_PlantCode_MTE__c</fullName>
    <label>プラント (MTE)</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/COWO_ProfitCenter__c.field-meta.xml
<CustomField>
    <fullName>COWO_ProfitCenter__c</fullName>
    <label>利益センタ(STE)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/COWO_ProfitCenter_MTE__c.field-meta.xml
<CustomField>
    <fullName>COWO_ProfitCenter_MTE__c</fullName>
    <formula>Quote.Opportunity.SAWO_ProfitCenter_MTE__c</formula>
    <label>利益センタ(MTE)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/COWO_QuantityUnit__c.field-meta.xml
<CustomField>
    <fullName>COWO_QuantityUnit__c</fullName>
    <description>S4連携項目</description>
    <label>基本数量単位</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MT</fullName>
                <label>MT:後で修正</label>
            </value>
            <value>
                <fullName>CV</fullName>
            </value>
            <value>
                <fullName>PC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/COWO_Recording_Division__c.field-meta.xml
<CustomField>
    <fullName>COWO_Recording_Division__c</fullName>
    <label>計上区分</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Z0</fullName>
                <label>Z0:完納</label>
            </value>
            <value>
                <fullName>Z1</fullName>
                <label>Z1:分納</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/COWO_RejectionReason__c.field-meta.xml
<CustomField>
    <fullName>COWO_RejectionReason__c</fullName>
    <label>拒否理由</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Z1</fullName>
                <label>Z1:キャンセル</label>
            </value>
            <value>
                <fullName>00</fullName>
                <label>00:Assigned by the System (Internal)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/COWO_SalesUnit__c.field-meta.xml
<CustomField>
    <fullName>COWO_SalesUnit__c</fullName>
    <label>販売単位</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>%</fullName>
            </value>
            <value>
                <fullName>%O</fullName>
            </value>
            <value>
                <fullName>°F</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>22S</fullName>
            </value>
            <value>
                <fullName>33</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>ACR</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>BAG</fullName>
            </value>
            <value>
                <fullName>BAR</fullName>
            </value>
            <value>
                <fullName>bbl</fullName>
            </value>
            <value>
                <fullName>bft</fullName>
            </value>
            <value>
                <fullName>bgl</fullName>
            </value>
            <value>
                <fullName>BQK</fullName>
            </value>
            <value>
                <fullName>Bqm</fullName>
            </value>
            <value>
                <fullName>bsc</fullName>
            </value>
            <value>
                <fullName>btl</fullName>
            </value>
            <value>
                <fullName>BTU</fullName>
            </value>
            <value>
                <fullName>BYr</fullName>
            </value>
            <value>
                <fullName>C3S</fullName>
            </value>
            <value>
                <fullName>CAN</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CCM</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CD3</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/COWO_StorageLocation__c.field-meta.xml
<CustomField>
    <fullName>COWO_StorageLocation__c</fullName>
    <label>保管場所(STE)</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/COWO_StorageLocation_MTE__c.field-meta.xml
<CustomField>
    <fullName>COWO_StorageLocation_MTE__c</fullName>
    <description>S4連携用項目</description>
    <label>保管場所(MTE)</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QLIPickListSupportController.cls
public with sharing class QLIPickListSupportController {
    public QLIPickListSupportController() {}

    /**
     * 画面初期処理
     * @param 見積品目Id
     * @return 結果
     */
    @AuraEnabled
    public static String init(String quoteLineItemId,
                              String selectQuantityUnit,
                              String selectDetailCategory,
                              String selectDetailCategoryMTE,
                              String selectRejectionReason,
                              String selectPlantCode,
                              String selectPlantCodeMTE,
                              String selectStorageLocation,
                              String selectStorageLocationMTE,
                              String selectCurrency,
                              String selectRecordingDivision,
                              String selectProfitCenter,
                              String selectProfitCenterMTE,
                              String selectMaterialGroup1,
                              String selectSalesUnit){
                              
        //QuoteLineItem qli = [select id,COWO_quantityUnit__c,COWO_DetailCategory__c,COWO_RejectionReason__c,COWO_PlantCode__c,COWO_PlantCode_MTE__c,COWO_StorageLocation__c,COWO_StorageLocation_MTE__c,COWO_Currency__c,COWO_Recording_Division__c,COWO_ProfitCenter__c,COWO_ProfitCenter_MTE__c,COWO_MaterialGroup1__c from QuoteLineItem where Id =: quoteLineItemId];

        UTL_CO_OvcSapPlant sap = new UTL_CO_OvcSapPlant();
        //UTL_CO_OvcSapPlant.UTL_CO_PlantAll res = sap.getOrgInfo('1710', '1000', '1000');
        //UTL_CO_OvcSapPlant.UTL_CO_PlantAll res = sap.getOrgInfo('1710', '1000', qli.COWO_PlantCode__c);
        UTL_CO_OvcSapPlant.UTL_CO_PlantAll res = sap.getOrgInfo('1710', '1000', selectPlantCode);
        
        // 型式の選択リスト定義を取得する
        /*List<SerializableSelectOption> quantityUnitOptions = getSalutationPicklist(new SerializableSelectOption('', '--',FALSE), 'QuoteLineItem', 'COWO_QuantityUnit__c',(String)initPicklistMap.get('selectQuantityUnit'));//getSalutationPicklist(new SerializableSelectOption('', '--',FALSE), 'QuoteLineItem', 'COWO_QuantityUnit__c');
        List<SerializableSelectOption> detailCategoryOptions = getSalutationPicklist(new SerializableSelectOption('', '--',FALSE), 'QuoteLineItem', 'COWO_DetailCategory__c',qli.COWO_DetailCategory__c);
        List<SerializableSelectOption> rejectionReasonOptions = getSalutationPicklist(new SerializableSelectOption('', '--',FALSE), 'QuoteLineItem', 'COWO_RejectionReason__c',qli.COWO_RejectionReason__c);
        List<SerializableSelectOption> plantCodeOptions = getS4SalutationPicklist(new SerializableSelectOption('', '--',FALSE), res, 'plantSTE',qli.COWO_PlantCode__c);
        List<SerializableSelectOption> plantCodeMTEOptions = getS4SalutationPicklist(new SerializableSelectOption('', '--',FALSE), res, 'plantMTE',qli.COWO_PlantCode_MTE__c);//plantSelectOptions;
        List<SerializableSelectOption> storageLocationOptions = getS4SalutationPicklist(new SerializableSelectOption('', '--',FALSE), res, 'storageLocSTE',qli.COWO_StorageLocation__c);//storageLocationOptionSTE;
        List<SerializableSelectOption> storageLocationMTEOptions = getS4SalutationPicklist(new SerializableSelectOption('', '--',FALSE), res, 'storageLocMTE',qli.COWO_StorageLocation_MTE__c);//storageLocationOptionMTE;
        List<SerializableSelectOption> currencyOptions = getSalutationPicklist(new SerializableSelectOption('', '--',FALSE), 'QuoteLineItem', 'CurrencyISOCode',qli.COWO_Currency__c);
        List<SerializableSelectOption> recordingDivisionOptions = getSalutationPicklist(new SerializableSelectOption('', '--',FALSE), 'QuoteLineItem', 'COWO_Recording_Division__c',qli.COWO_Recording_Division__c);
        List<SerializableSelectOption> profitCenterOptions = getS4SalutationPicklist(new SerializableSelectOption('', '--',FALSE), res, 'profitCenterSTE',qli.COWO_ProfitCenter__c);//profitCenterOptionSTE;
        List<SerializableSelectOption> profitCenterMTEOptions = getS4SalutationPicklist(new SerializableSelectOption('', '--',FALSE), res, 'profitCenterMTE',qli.COWO_ProfitCenter_MTE__c);//profitCenterOptionMTE;
        List<SerializableSelectOption> materialGroup1Options = getSalutationPicklist(new SerializableSelectOption('', '--',FALSE), 'QuoteLineItem', 'COWO_MaterialGroup1__c',qli.COWO_MaterialGroup1__c);*/ 
        List<SerializableSelectOption> quantityUnitOptions = getSalutationPicklist(new SerializableSelectOption('', '--',FALSE), 'QuoteLineItem', 'COWO_QuantityUnit__c',selectQuantityUnit);//getSalutationPicklist(new SerializableSelectOption('', '--',FALSE), 'QuoteLineItem', 'COWO_QuantityUnit__c');
        List<SerializableSelectOption> detailCategoryOptions = getSalutationPicklist(new SerializableSelectOption('', '--',FALSE), 'QuoteLineItem', 'COWO_DetailCategory__c',selectDetailCategory);
        List<SerializableSelectOption> detailCategoryMTEOptions = getSalutationPicklist(new SerializableSelectOption('', '--',FALSE), 'QuoteLineItem', 'COWO_DetailCategory_MTE__c',selectDetailCategoryMTE);
        List<SerializableSelectOption> rejectionReasonOptions = getSalutationPicklist(new SerializableSelectOption('', '--',FALSE), 'QuoteLineItem', 'COWO_RejectionReason__c',selectRejectionReason);
        List<SerializableSelectOption> plantCodeOptions = getS4SalutationPicklist(new SerializableSelectOption('', '--',FALSE), res, 'plantSTE',selectPlantCode);
        List<SerializableSelectOption> plantCodeMTEOptions = getS4SalutationPicklist(new SerializableSelectOption('', '--',FALSE), res, 'plantMTE',selectPlantCodeMTE);//plantSelectOptions;
        List<SerializableSelectOption> storageLocationOptions = getS4SalutationPicklist(new SerializableSelectOption('', '--',FALSE), res, 'storageLocSTE',selectStorageLocation);//storageLocationOptionSTE;
        List<SerializableSelectOption> storageLocationMTEOptions = getS4SalutationPicklist(new SerializableSelectOption('', '--',FALSE), res, 'storageLocMTE',selectStorageLocationMTE);//storageLocationOptionMTE;
        List<SerializableSelectOption> currencyOptions = getSalutationPicklist(new SerializableSelectOption('', '--',FALSE), 'QuoteLineItem', 'CurrencyISOCode',selectCurrency);
        List<SerializableSelectOption> recordingDivisionOptions = getSalutationPicklist(new SerializableSelectOption('', '--',FALSE), 'QuoteLineItem', 'COWO_Recording_Division__c',selectRecordingDivision);
        List<SerializableSelectOption> profitCenterOptions = getS4SalutationPicklist(new SerializableSelectOption('', '--',FALSE), res, 'profitCenterSTE',selectProfitCenter);//profitCenterOptionSTE;
        List<SerializableSelectOption> profitCenterMTEOptions = getS4SalutationPicklist(new SerializableSelectOption('', '--',FALSE), res, 'profitCenterMTE',selectProfitCenterMTE);//profitCenterOptionMTE;
        List<SerializableSelectOption> materialGroup1Options = getSalutationPicklist(new SerializableSelectOption('', '--',FALSE), 'QuoteLineItem', 'COWO_MaterialGroup1__c',selectMaterialGroup1);
        List<SerializableSelectOption> salesUnitOptions = getSalutationPicklist(new SerializableSelectOption('', '--',FALSE), 'QuoteLineItem', 'COWO_SalesUnit__c',selectSalesUnit);

        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        gen.writeNumberField('returnCode', 0); // 正常終了
        gen.writeObjectField('COWO_QuantityUnit__c', quantityUnitOptions);
        gen.writeObjectField('COWO_DetailCategory__c', detailCategoryOptions);
        gen.writeObjectField('COWO_DetailCategory_MTE__c', detailCategoryMTEOptions);
        gen.writeObjectField('COWO_RejectionReason__c', rejectionReasonOptions);
        gen.writeObjectField('COWO_PlantCode__c', plantCodeOptions);
        gen.writeObjectField('COWO_PlantCode_MTE__c', plantCodeMTEOptions);
        gen.writeObjectField('COWO_StorageLocation__c', storageLocationOptions);
        gen.writeObjectField('COWO_StorageLocation_MTE__c', storageLocationMTEOptions);
        gen.writeObjectField('COWO_Currency__c', currencyOptions);
        gen.writeObjectField('COWO_Recording_Division__c', recordingDivisionOptions);
        gen.writeObjectField('COWO_ProfitCenter__c', profitCenterOptions);
        gen.writeObjectField('COWO_ProfitCenter_MTE__c', profitCenterMTEOptions);
        gen.writeObjectField('COWO_MaterialGroup1__c', materialGroup1Options);
        gen.writeObjectField('COWO_SalesUnit__c', salesUnitOptions);
        gen.writeEndObject();
        
        // Get the JSON string.
        String JSONString = gen.getAsString();

        return JSONString;
    }

    /**
     * plantSTE Changeイベント処理
     * @param plantste
     * @return 結果
     */
    @AuraEnabled
    public static String getStorageSTEByPlantste(String plantste){
        System.debug('plantste' + plantste);
        /*UTL_CO_OvcSapPlant sap = new UTL_CO_OvcSapPlant();
        //UTL_CO_OvcSapPlant.UTL_CO_PlantAll res = sap.getOrgInfo('1710', '1000', '1000');
        UTL_CO_OvcSapPlant.UTL_CO_PlantAll res = sap.getOrgInfo('1710', '1000',plantste);
        List<SerializableSelectOption> storageLocationOptions = getS4SalutationPicklist(new SerializableSelectOption('', '--',FALSE), res, 'storageLocSTE','');//storageLocationOptionSTE;
*/
        UTL_CO_OvcSapPlant sap = new UTL_CO_OvcSapPlant();
        UTL_CO_OvcSapPlant.UTL_CO_PlantAll res = sap.getOrgInfo('1710', '1000',plantste);
        List<SerializableSelectOption> storageLocationOptions = getS4SalutationPicklist(new SerializableSelectOption('', '--',FALSE), res, 'storageLocSTE','');//storageLocationOptionSTE;
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        gen.writeNumberField('returnCode', 0); // 正常終了
        gen.writeObjectField('COWO_StorageLocation__c', storageLocationOptions);
        gen.writeEndObject();

        // Get the JSON string.
        String JSONString = gen.getAsString();

        return JSONString;
        

    }

    private static Map<String, String> picklistValues(String objectName, String fieldName) {
        Map<String, String> values = new Map<String, String>{};

        List<Schema.DescribeSobjectResult> results = Schema.describeSObjects(new List<String>{objectName});
        
        for(Schema.DescribeSobjectResult res : results) {
            for (Schema.PicklistEntry entry : res.fields.getMap().get(fieldName).getDescribe().getPicklistValues()) {
                if (entry.isActive()) {
                    if(fieldName.equals('CurrencyISOCode')){
                        values.put(entry.getValue(), entry.getValue() +':'+ entry.getLabel());
                    }else {
                        values.put(entry.getValue(), entry.getLabel());
                    }
                }
            }
        }

        return values;
    }

    private static Map<String, String> pickS4listValues(UTL_CO_OvcSapPlant.UTL_CO_PlantAll plantAll,String fieldName) {
        Map<String, String> values = new Map<String, String>{};

        List<UTL_CO_OvcSapPlant.UTL_CO_Plant> plantList = plantAll.plantMte;
        List<UTL_CO_OvcSapPlant.UTL_CO_StorageLocation> storageLocSteList = plantAll.storageLocSte;
        List<UTL_CO_OvcSapPlant.UTL_CO_ProfitCenter> profitCenterMTEList = plantAll.profitCenterMte;
        List<UTL_CO_OvcSapPlant.UTL_CO_ProfitCenter> profitCenterSTEList = plantAll.profitCenterSte;
        List<UTL_CO_OvcSapPlant.UTL_CO_StorageLocation> storageLocationList = new List<UTL_CO_OvcSapPlant.UTL_CO_StorageLocation>();
        if(fieldName.equals('plantMTE')){
            for(UTL_CO_OvcSapPlant.UTL_CO_Plant plant : plantList){
                values.put(plant.code, plant.code + ':' + plant.text);
            }
        }else if(fieldName.equals('plantSTE')){
                values.put('1000', '1000:日立ハイテク（本社）');
                values.put('1010', '1010:日立ハイテク（那珂）');
                values.put('1020', '1020:日立ハイテク（笠戸）');
                values.put('1030', '1030:日立ハイテク（大牟田）');
        }else if(fieldName.equals('storageLocMTE')){
            storageLocationList = plantList[0].storageLocations;
            for(UTL_CO_OvcSapPlant.UTL_CO_StorageLocation storageLocation : storageLocationList){
                values.put(storageLocation.code,storageLocation.code  + ':' + storageLocation.text);
            }
        }else if(fieldName.equals('storageLocSTE')){
            for(UTL_CO_OvcSapPlant.UTL_CO_StorageLocation storageLocationSTE : storageLocSteList){
                values.put(storageLocationSTE.code,storageLocationSTE.code  + ':' + storageLocationSTE.text);
            }
        }
        else if(fieldName.equals('profitCenterMTE')){
            for(UTL_CO_OvcSapPlant.UTL_CO_ProfitCenter profitCenterMTE : profitCenterMTEList){
                values.put(profitCenterMTE.code,profitCenterMTE.code  + ':' + profitCenterMTE.text);
            }
        }else if(fieldName.equals('profitCenterSTE')){
            for(UTL_CO_OvcSapPlant.UTL_CO_ProfitCenter profitCenterSTE : profitCenterSTEList){
                values.put(profitCenterSTE.code,profitCenterSTE.code  + ':' + profitCenterSTE.text);
            }
        }
        return values;
    }

    /*public static List<SerializableSelectOption> getSalutationPicklist(SerializableSelectOption selectOption, String objectName, String fieldName) {
        List<SerializableSelectOption> selectOptions = new List<SerializableSelectOption>();
        if(selectOption != null){
            selectOptions.add(selectOption);
        }

        Map<String, String> salutationValueLabels = picklistValues(objectName, fieldName);
        for (String value : salutationValueLabels.keySet()) {
            selectOptions.add(new SerializableSelectOption(value, salutationValueLabels.get(value)));
        }

        return selectOptions;
    }*/

    private static List<SerializableSelectOption> getSalutationPicklist(SerializableSelectOption selectOption, String objectName, String fieldName,String selectValue) {
        List<SerializableSelectOption> selectOptions = new List<SerializableSelectOption>();
        if(selectOption != null){
            selectOptions.add(selectOption);
        }
        Map<String, String> salutationValueLabels = picklistValues(objectName, fieldName);
        for (String value : salutationValueLabels.keySet()) {
            Boolean selected = false;
            if(selectValue != null && value.equals(selectValue)){
                selected = true;
            }
            selectOptions.add(new SerializableSelectOption(value, salutationValueLabels.get(value),selected));
        }

        return selectOptions;
    }

    /*public static List<SerializableSelectOption> getS4SalutationPicklist(SerializableSelectOption selectOption, UTL_CO_OvcSapPlant.UTL_CO_PlantAll plantAll,String fieldName) {
        List<SerializableSelectOption> selectOptions = new List<SerializableSelectOption>();
        if(selectOption != null){
            selectOptions.add(selectOption);
        }
        Map<String, String> salutationValueLabels = pickS4listValues(plantAll,fieldName);
        for (String value : salutationValueLabels.keySet()) {
            selectOptions.add(new SerializableSelectOption(value, salutationValueLabels.get(value)));
        }
        return selectOptions;
    }*/

    private static List<SerializableSelectOption> getS4SalutationPicklist(SerializableSelectOption selectOption, UTL_CO_OvcSapPlant.UTL_CO_PlantAll plantAll,String fieldName,String selectValue) {
        List<SerializableSelectOption> selectOptions = new List<SerializableSelectOption>();
        if(selectOption != null){
            selectOptions.add(selectOption);
        }
        Map<String, String> salutationValueLabels = pickS4listValues(plantAll,fieldName);
        for (String value : salutationValueLabels.keySet()) {
            Boolean selected = false;
            if(selectValue != null && value.equals(selectValue)){
                selected = true;
            }
            selectOptions.add(new SerializableSelectOption(value, salutationValueLabels.get(value),selected));
        }
        return selectOptions;
    }
    
    public class SerializableSelectOption {

        public String label {get; set;}
        public String value {get; set;}
        public Boolean selected{get; set;}

        public SerializableSelectOption(SelectOption so) {
            this.label = so.getLabel();
            this.value = so.getValue();
            this.selected = false;
        }

        public SerializableSelectOption(PicklistEntry pe) {
            this.label = pe.getLabel();
            this.value = pe.getValue();
            this.selected = false;
        }

        public SerializableSelectOption(String label, String value,Boolean selected) {
            this.label = label;
            this.value = value;
            this.selected = selected;
        }
    }
}