force-app/main/default/objects/COWO_QuoteLineItem__c/COWO_QuoteLineItem__c.object-meta.xml
<CustomObject>
    <description>DX</description>
    <label>見積帳票明細</label>
    <nameField>
        <displayFormat>QL-{0000000000}</displayFormat>
        <label>見積帳票明細名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/COWO_QuoteLineItem__c/fields/COWO_Quote__c.field-meta.xml
<CustomField>
    <fullName>COWO_Quote__c</fullName>
    <label>見積</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>見積帳票明細</relationshipLabel>
    <relationshipName>COWO_QuoteLineItem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/COWO_QuoteLineItem__c/fields/COWO_SortNo__c.field-meta.xml
<CustomField>
    <fullName>COWO_SortNo__c</fullName>
    <label>並び順</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COWO_FrontPurchasePrice__c.field-meta.xml
<CustomField>
    <fullName>COWO_FrontPurchasePrice__c</fullName>
    <label>フロント仕入価格</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COWO_LocalCorporationTC__c.field-meta.xml
<CustomField>
    <fullName>COWO_LocalCorporationTC__c</fullName>
    <label>現法TC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COWO_MC__c.field-meta.xml
<CustomField>
    <fullName>COWO_MC__c</fullName>
    <label>MC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/COWO_TC__c.field-meta.xml
<CustomField>
    <fullName>COWO_TC__c</fullName>
    <label>TC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MC__c.field-meta.xml
<CustomField>
    <fullName>MC__c</fullName>
    <inlineHelpText>原価</inlineHelpText>
    <label>MC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/TC__c.field-meta.xml
<CustomField>
    <fullName>TC__c</fullName>
    <inlineHelpText>トータルコスト</inlineHelpText>
    <label>TC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/COWO_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>COWO_Approval_Status__c</fullName>
    <label>承認ステータス</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>未申請</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>申請中</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>承認済</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/COWO_ApprovalDate1__c.field-meta.xml
<CustomField>
    <fullName>COWO_ApprovalDate1__c</fullName>
    <description>見積承認1が承認された日時</description>
    <label>見積承認日時1</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote/fields/COWO_ApprovalDate2__c.field-meta.xml
<CustomField>
    <fullName>COWO_ApprovalDate2__c</fullName>
    <description>見積承認2が承認された日時</description>
    <label>見積承認日時2</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote/fields/COWO_ApprovalSkipFlag__c.field-meta.xml
<CustomField>
    <fullName>COWO_ApprovalSkipFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>承認スキップフラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/COWO_ApprovalStartFlag__c.field-meta.xml
<CustomField>
    <fullName>COWO_ApprovalStartFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>承認申請開始フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/COWO_Authorizer1__c.field-meta.xml
<CustomField>
    <fullName>COWO_Authorizer1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>承認者1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>COWO_Authorizer1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/COWO_Authorizer2__c.field-meta.xml
<CustomField>
    <fullName>COWO_Authorizer2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>承認者2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>COWO_Authorizer2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/COWO_Circulation__c.field-meta.xml
<CustomField>
    <fullName>COWO_Circulation__c</fullName>
    <defaultValue>1</defaultValue>
    <description>顧客へ提出した見積書の部数</description>
    <label>提出部数</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/COWO_CopyFlag__c.field-meta.xml
<CustomField>
    <fullName>COWO_CopyFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>見積コピー機能を使用して作成された見積の場合Trueとする。
当項目がTrueである場合AfterInsertトリガが起動されない</description>
    <label>コピーフラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/COWO_Customer_Adopted_Quote__c.field-meta.xml
<CustomField>
    <fullName>COWO_Customer_Adopted_Quote__c</fullName>
    <defaultValue>false</defaultValue>
    <label>顧客採用見積</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/COWO_Customer_Presented_Quote__c.field-meta.xml
<CustomField>
    <fullName>COWO_Customer_Presented_Quote__c</fullName>
    <defaultValue>false</defaultValue>
    <label>顧客提示済見積</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/COWO_FollowApproval__c.field-meta.xml
<CustomField>
    <fullName>COWO_FollowApproval__c</fullName>
    <defaultValue>false</defaultValue>
    <description>承認者が追認処理を実施した際にチェックを付けます。</description>
    <label>追認承認</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/COWO_FollowApprovalDate__c.field-meta.xml
<CustomField>
    <fullName>COWO_FollowApprovalDate__c</fullName>
    <description>追認を実施した時間が登録されます。</description>
    <label>追認日付</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote/fields/COWO_FollowApprover__c.field-meta.xml
<CustomField>
    <fullName>COWO_FollowApprover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>見積の追認実施者が設定されます。</description>
    <label>追認承認者</label>
    <referenceTo>User</referenceTo>
    <relationshipName>FollowApproverUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/COWO_Imprint1__c.field-meta.xml
<CustomField>
    <fullName>COWO_Imprint1__c</fullName>
    <label>押印1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/COWO_Imprint2__c.field-meta.xml
<CustomField>
    <fullName>COWO_Imprint2__c</fullName>
    <label>押印2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/COWO_Imprint3__c.field-meta.xml
<CustomField>
    <fullName>COWO_Imprint3__c</fullName>
    <label>押印3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/COWO_Quote_Create_Date__c.field-meta.xml
<CustomField>
    <fullName>COWO_Quote_Create_Date__c</fullName>
    <label>見積日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/COWO_QuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>COWO_QuoteNumber__c</fullName>
    <label>見積番号</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/COWO_FrontPurchasePrice__c.field-meta.xml
<CustomField>
    <fullName>COWO_FrontPurchasePrice__c</fullName>
    <description>フロント営業がHHTおよびサプライヤーから仕入れる価格</description>
    <label>フロント仕入価格</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/COWO_LocalCorporationTC__c.field-meta.xml
<CustomField>
    <fullName>COWO_LocalCorporationTC__c</fullName>
    <description>フロント仕入価格+フロント販売管理費など</description>
    <label>現法TC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/COWO_MC__c.field-meta.xml
<CustomField>
    <fullName>COWO_MC__c</fullName>
    <description>製造原価</description>
    <label>MC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/COWO_SortNo__c.field-meta.xml
<CustomField>
    <fullName>COWO_SortNo__c</fullName>
    <label>並び順</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/COWO_TC__c.field-meta.xml
<CustomField>
    <fullName>COWO_TC__c</fullName>
    <description>製造原価＋販売管理費など</description>
    <label>TC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/COWO_TotalFrontPurchasePrice__c.field-meta.xml
<CustomField>
    <fullName>COWO_TotalFrontPurchasePrice__c</fullName>
    <description>フロント仕入価格×数量
トリガにて計算を実施、ページレイアウトで編集不可とすること</description>
    <label>総フロント仕入価格</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/COWO_TotalLocalCorporationTC__c.field-meta.xml
<CustomField>
    <fullName>COWO_TotalLocalCorporationTC__c</fullName>
    <description>現法TC×数量
トリガにて計算を実施、ページレイアウトで編集不可とすること</description>
    <label>総現法TC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/COWO_TotalMC__c.field-meta.xml
<CustomField>
    <fullName>COWO_TotalMC__c</fullName>
    <description>MC×数量
トリガにて計算を実施、ページレイアウトで編集不可とすること</description>
    <label>総MC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/COWO_TotalTC__c.field-meta.xml
<CustomField>
    <fullName>COWO_TotalTC__c</fullName>
    <description>TC×数量
トリガにて計算を実施、ページレイアウトで編集不可とすること</description>
    <label>総TC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Quote_DXCopyClass.cls
/********************************************************************************
 * クラス名 ： Quote_DXCopyClass
 * 概　　要 ： 見積のコピーボタンから呼ばれるクラス
 *             見積、見積品目名、見積帳票明細オブジェクトのコピーを行う
 * 作 成 日 ： 2020/01/28 sakamoto
 * 更 新 日 ：
 ********************************************************************************/

global class Quote_DXCopyClass {
    
   /*
    *コンストラクタ
    */
    public Quote_DXCopyClass(){}
    
    /**
     * webservice String copyQuote()
     * 見積、見積品目名、見積帳票明細オブジェクトのコピーを行う。
     * isUpdatePriceがTrueの場合には価格表より価格の更新を行う。
     * @param ID targetQuoteId コピー元の見積ID
     * @param Boolean isUpdatePrice 価格更新フラグ
     * @return String
     * 正常終了 -> 作成された見積のId 異常終了 -> 'false'を返却
     */
    @AuraEnabled
    webService static String copyQuote(Id targetQuoteId,Boolean isUpdatePrice){
        // セーブポイント設定
        SavePoint sp = Database.setSavePoint();
        String result = 'false';
        
        // 項目取得のSOQL作成
        String queryStringQuote = 'SELECT\t';
        queryStringQuote += getFieldsNameStr(targetQuoteId.getSObjectType());
        queryStringQuote += '\tFROM Quote where ID = :targetQuoteId';
        
        // 見積品目名のスキーマ情報取得、クエリ文字列に追加
        String queryStringQuoteLineItem = 'SELECT\tProduct2.Name,\t';
        queryStringQuoteLineItem += getFieldsNameStr(Schema.QuoteLineItem.getSObjectType());
        queryStringQuoteLineItem += '\tFROM QuoteLineItem where QuoteId = :targetQuoteId';
        queryStringQuoteLineItem += '\tORDER BY COWO_SortNo__c';
            
        // 見積帳票明細のスキーマ情報取得、クエリ文字列に追加
        String queryStringCOWO_QuoteLineItem = 'SELECT\t';
        queryStringCOWO_QuoteLineItem += getFieldsNameStr(Schema.COWO_QuoteLineItem__c.getSObjectType());
        queryStringCOWO_QuoteLineItem += '\tFROM COWO_QuoteLineItem__c where COWO_Quote__c = :targetQuoteId';
        queryStringCOWO_QuoteLineItem += '\tORDER BY COWO_SortNo__c';

        system.debug(queryStringQuote);
        system.debug(queryStringQuoteLineItem);
        system.debug(queryStringCOWO_QuoteLineItem);

   	    try{
            Quote copyFromQuote = Database.query(queryStringQuote);
            Quote copyToQuote   = copyFromQuote.clone();
            
            List<QuoteLineItem> copyFromQuoteLineItemList = Database.query(queryStringQuoteLineItem);
            List<COWO_QuoteLineItem__c> copyFromCOWO_QuoteLineItemList = Database.query(queryStringCOWO_QuoteLineItem);
            
            //項目の初期化
            copyToQuote.Name += '_copy';
            copyToQuote.Status	= null;
            copyToQuote.COWO_QuoteNumber__c = null;
			copyToQuote.COWO_Customer_Presented_Quote__c = false;
		    copyToQuote.COWO_Customer_Adopted_Quote__c = false;
            copyToQuote.COWO_Authorizer1__c	= null;
            copyToQuote.COWO_Authorizer2__c	= null;
            copyToQuote.COWO_ApprovalDate1__c = null;
            copyToQuote.COWO_ApprovalDate2__c = null;
            copyToQuote.COWO_Imprint1__c	= null;
            copyToQuote.COWO_Imprint2__c	= null;
            copyToQuote.COWO_Imprint3__c	= null;
            copyToQuote.COWO_Approval_Status__c	= null;
            copyToQuote.COWO_ApprovalSkipFlag__c	= false;
            copyToQuote.COWO_ApprovalStartFlag__c	= false;
            copyToQuote.COWO_Quote_Create_Date__c	= date.today();
            copyToQuote.COWO_FollowApproval__c = False;
            copyToQuote.COWO_FollowApprover__c = null;
            copyToQuote.COWO_FollowApprovalDate__c = null;
            copyToQuote.COWO_Circulation__c = 1;
            copyToQuote.OwnerId = System.UserInfo.getUserId();//担当者をコピー実施者へ変更
            copyToQuote.COWO_CopyFlag__c    = True; //コピー機能で作成された見積のフラグ　Trueの場合AfterInsertトリガが起動しない
            
            //見積のインサート
            insert copyToQuote;
            
            //価格表エントリ情報取得
            Map<String,PriceBookEntry> priceBookEntryMap;
            Map<String,Product2> product2Map;
            if(isUpdatePrice){
                // 価格表から更新する場合、見積品目名の価格表エントリIDから価格表エントリを取得する。
                Set<Id> priceBookEntryIdSet = new Set<Id>();
                Set<Id> productIdSet = new Set<Id>();
                for(QuoteLineItem copyFromQuoteLineItem:copyFromQuoteLineItemList){
                    priceBookEntryIdSet.add(copyFromQuoteLineItem.PriceBookEntryId); //Todo 一旦仕様確定までは商品から取得する様にする。
                    productIdSet.add(copyFromQuoteLineItem.Product2Id);
                }
                //価格表エントリより項目を取得する。
                priceBookEntryMap = new Map<String,PriceBookEntry>
                    ([select id,UnitPrice,COWO_MC__c,COWO_TC__c,COWO_FrontPurchasePrice__c,COWO_LocalCorporationTC__c from PriceBookEntry where id in :priceBookEntryIdSet]);
                product2Map = new Map<String,Product2>//Todo 一旦仕様確定までは商品から取得する様にする。
                    ([select id,MC__c,TC__c from Product2 where id in :productIdSet]);
                System.debug(product2Map);
            }
            
            // Insertした見積と見積品目名の紐づけ
            List<QuoteLineItem> copyToQuoteLineItemList = new List<QuoteLineItem>();
            for(QuoteLineItem copyFromQuoteLineItem:copyFromQuoteLineItemList){
            	QuoteLineItem copyToQuoteLineItem = copyFromQuoteLineItem.clone();
                copyToQuoteLineItem.QuoteId = copyToQuote.Id;
                
                if(isUpdatePrice && copyToQuoteLineItem.Product2.Name != System.Label.AP00_CONST_0001 ){ // 現在の価格表の価格で見積の価格を更新する場合の処理
                	//いいえを選択された場合または自由入力商品については価格の更新を行わない
                	priceBookEntry pbe = priceBookEntryMap.get(copyToQuoteLineItem.PricebookEntryId);
                    Product2 pro = product2Map.get(copyToQuoteLineItem.Product2Id);//Todo 一旦仕様確定までは商品から取得する様にする。
                	system.debug(pbe);
                	if(pbe != null){
						//価格表エントリから値を取得する
                    	copyToQuoteLineItem.UnitPrice = pbe.UnitPrice;
						//copyToQuoteLineItem.COWO_MC__c = pbe.COWO_MC__c != null ?  pbe.COWO_MC__c : 0;
    					//copyToQuoteLineItem.COWO_TC__c = pbe.COWO_TC__c != null ?  pbe.COWO_TC__c : 0;
    					copyToQuoteLineItem.COWO_LocalCorporationTC__c = pbe.COWO_LocalCorporationTC__c != null ?  pbe.COWO_LocalCorporationTC__c : 0;
    					copyToQuoteLineItem.COWO_FrontPurchasePrice__c = pbe.COWO_FrontPurchasePrice__c != null ?  pbe.COWO_FrontPurchasePrice__c : 0;
    					copyToQuoteLineItem.COWO_MC__c = pro.MC__c != null ?  pro.MC__c : 0;//Todo 一旦仕様確定までは商品から取得する様にする。
    					copyToQuoteLineItem.COWO_TC__c = pro.TC__c != null ?  pro.TC__c : 0;

                        //合計計算
                        Decimal quantity = (Decimal)copyToQuoteLineItem.Quantity;               
                        copyToQuoteLineItem.COWO_TotalMC__c = quantity * copyToQuoteLineItem.COWO_MC__c;
                        copyToQuoteLineItem.COWO_TotalTC__c = quantity * copyToQuoteLineItem.COWO_TC__c;
                        copyToQuoteLineItem.COWO_TotalLocalCorporationTC__c = quantity * copyToQuoteLineItem.COWO_LocalCorporationTC__c;
                        copyToQuoteLineItem.COWO_TotalFrontPurchasePrice__c = quantity * copyToQuoteLineItem.COWO_FrontPurchasePrice__c;
                    }
                }
                
                //編集した内容を見積商品名リストに設定する
                copyToQuoteLineItemList.add(copyToQuoteLineItem);
                
       		}
            
            // Insertした見積と見積帳票明細の紐づけ
            List<COWO_QuoteLineItem__c> copyToCOWO_QuoteLineItemList = new List<COWO_QuoteLineItem__c>();
            for(COWO_QuoteLineItem__c copyFromCOWO_QuoteLineItem:copyFromCOWO_QuoteLineItemList){
            	COWO_QuoteLineItem__c copyToCOWO_QuoteLineItem = copyFromCOWO_QuoteLineItem.clone();
                copyToCOWO_QuoteLineItem.COWO_Quote__c = copyToQuote.Id;
                
                //編集した内容を見積帳票明細リストに設定する
                copyToCOWO_QuoteLineItemList.add(copyToCOWO_QuoteLineItem);
                
       		}
            // 見積製品、見積明細のInsert
            insert copyToQuoteLineItemList;
            insert copyToCOWO_QuoteLineItemList;

			result = copyToQuote.Id;
        } catch(Exception e){
            Database.rollback(sp);
            System.debug(e);
        }
        return result;
    }
    
    /**
     * private  getField
     * 引数に渡されたオブジェクトの項目をカンマ区切りの文字列へ変換する。
     * @param Schema.SObjectType
     * @return String　オブジェクトの項目をカンマ区切りで作成した文字列
     */
    private static String getFieldsNameStr(Schema.SObjectType objType){
        Schema.DescribeSObjectResult sobj = objType.getDescribe();
        Map<String,Schema.SObjectField> sobjFieldsMap = sobj.fields.getMap();
        return String.join(new List<String>(sobjFieldsMap.keySet()), ',');

    }

}