force-app/main/default/objects/Opportunity/fields/ItemName__c.field-meta.xml
<CustomField>
    <fullName>ItemName__c</fullName>
    <label>品名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Katashiki__c.field-meta.xml
<CustomField>
    <fullName>Katashiki__c</fullName>
    <label>競合型式_HTD</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CompetitionMaker__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>C16000</fullName>
            </value>
            <value>
                <fullName>Ci16200</fullName>
            </value>
            <value>
                <fullName>C8000</fullName>
            </value>
            <value>
                <fullName>Ci8200</fullName>
            </value>
            <value>
                <fullName>AU480</fullName>
            </value>
            <value>
                <fullName>AU680</fullName>
            </value>
            <value>
                <fullName>AU5811</fullName>
            </value>
            <value>
                <fullName>AU5821</fullName>
            </value>
            <value>
                <fullName>AU5831</fullName>
            </value>
            <value>
                <fullName>AU5841</fullName>
            </value>
            <value>
                <fullName>DXC800</fullName>
            </value>
            <value>
                <fullName>cobas6000(501)</fullName>
            </value>
            <value>
                <fullName>cobas6000(502)</fullName>
            </value>
            <value>
                <fullName>cobas8000(701)</fullName>
            </value>
            <value>
                <fullName>cobas8000(702)</fullName>
            </value>
            <value>
                <fullName>cobas8000(702+502)</fullName>
            </value>
            <value>
                <fullName>cobas8000(702+701)</fullName>
            </value>
            <value>
                <fullName>cobas311</fullName>
            </value>
            <value>
                <fullName>ADVIA1200</fullName>
            </value>
            <value>
                <fullName>ADVIA1800</fullName>
            </value>
            <value>
                <fullName>ADVIA2400</fullName>
            </value>
            <value>
                <fullName>Dimension Xpand Plus</fullName>
            </value>
            <value>
                <fullName>Dimension RxL Max</fullName>
            </value>
            <value>
                <fullName>Dimension EXL200</fullName>
            </value>
            <value>
                <fullName>Dimension EXL with LM</fullName>
            </value>
            <value>
                <fullName>BM6010</fullName>
            </value>
            <value>
                <fullName>BM6010C</fullName>
            </value>
            <value>
                <fullName>BX-3010</fullName>
            </value>
            <value>
                <fullName>BX-4000</fullName>
            </value>
            <value>
                <fullName>120FR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/katashiki__c.field-meta.xml
<CustomField>
    <fullName>katashiki__c</fullName>
    <label>型式</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CountryMode__c.field-meta.xml
<CustomField>
    <fullName>CountryMode__c</fullName>
    <label>国モード</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ItemName__c.field-meta.xml
<CustomField>
    <fullName>ItemName__c</fullName>
    <label>製品名</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Katashiki__c.field-meta.xml
<CustomField>
    <fullName>Katashiki__c</fullName>
    <description>(補足)
型式の接頭辞として、以下の名前が付く場合は、案件製品一括編集画面で自由入力商品を選択した際の選択リストに表示される。

自社部品
HHS
商社品</description>
    <label>型式</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ItemDivision__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>SU9000</fullName>
            </value>
            <value>
                <fullName>SU8240(Regulus)</fullName>
            </value>
            <value>
                <fullName>SU8230(Regulus)</fullName>
            </value>
            <value>
                <fullName>SU8220(Regulus)</fullName>
            </value>
            <value>
                <fullName>SU8100</fullName>
            </value>
            <value>
                <fullName>SU8240</fullName>
            </value>
            <value>
                <fullName>SU8230</fullName>
            </value>
            <value>
                <fullName>SU8220</fullName>
            </value>
            <value>
                <fullName>SU8010</fullName>
            </value>
            <value>
                <fullName>SU5000</fullName>
            </value>
            <value>
                <fullName>SU-70</fullName>
            </value>
            <value>
                <fullName>SU7000</fullName>
            </value>
            <value>
                <fullName>SU3500(5MD)</fullName>
            </value>
            <value>
                <fullName>SU3500(4MD)</fullName>
            </value>
            <value>
                <fullName>S-3700N</fullName>
            </value>
            <value>
                <fullName>SU1510</fullName>
            </value>
            <value>
                <fullName>FlexSEM1000</fullName>
            </value>
            <value>
                <fullName>FlexSEM1000Ⅱ</fullName>
            </value>
            <value>
                <fullName>SU3900</fullName>
            </value>
            <value>
                <fullName>SU3800</fullName>
            </value>
            <value>
                <fullName>IM4000</fullName>
            </value>
            <value>
                <fullName>冷却付 IM4000</fullName>
            </value>
            <value>
                <fullName>IM4000PLUS</fullName>
            </value>
            <value>
                <fullName>冷却付 IM4000PLUS</fullName>
            </value>
            <value>
                <fullName>IM5000</fullName>
            </value>
            <value>
                <fullName>冷却付 IM5000</fullName>
            </value>
            <value>
                <fullName>MC1000</fullName>
            </value>
            <value>
                <fullName>TM3030</fullName>
            </value>
            <value>
                <fullName>TM3030Plus</fullName>
            </value>
            <value>
                <fullName>TM4000</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityLineItemBulkEditTest2.cls
@isTest
public with sharing class OpportunityLineItemBulkEditTest2 {

    class DraftValues {
        String Id{get; set;}
        String Name{get; set;}
        Integer Quantity{get; set;}
        Double UnitPrice{get; set;}
        String ServiceDate{get; set;}
        String Description{get; set;}
    }

    class DraftValues2 {
        String Id{get; set;}
        String Name{get; set;}
        String Quantity{get; set;}
        String UnitPrice{get; set;}
        String ServiceDate{get; set;}
        String Description{get; set;}
    }

    class DeletedData {
        String Id{get; set;}
    }

    /**
     * ＤＢ反映処理：正常終了の場合（追加商品）
     * 価格表エントリ(商談に紐づく価格表)が未登録
     * 価格表エントリ(標準価格表)が未登録
     * 
     */
     @isTest(SeeAllData=true)
    static void unitTest_001() {
        Opportunity opp = [select Id from Opportunity limit 1];
        OpportunityLineItem opportunityLineItem = [select Id from OpportunityLineItem limit 1];
        // 商品登録
        Product2 product2 = new Product2();
        product2.Name = 'Name';
        product2.IsActive = true;
        product2.CountryMode__c = 'J';  // TODO
        product2.Katashiki__c = 'SU8240(Regulus)';  // TODO
        product2.ItemName__c = 'ItemName';
        insert product2;
        
        // draftValues
        JSONGenerator gen = JSON.createGenerator(true);
        List<DraftValues> draftValuesList = new List<DraftValues>();
        DraftValues d = new DraftValues();
        d.Id = 'Add' + product2.Id;
        d.Name = 'Name';
        d.Quantity = 1;
        d.UnitPrice = 100.1;
        d.ServiceDate = '2019-12-05';
        d.Description = 'Description';
        draftValuesList.add(d);
        gen.writeObject(draftValuesList);
        String draftValues = gen.getAsString();

        // deletedData
        gen = JSON.createGenerator(true);
        List<DraftValues> deletedDataList = new List<DraftValues>();
        DraftValues del = new DraftValues();
        del.Id = opportunityLineItem.Id;
        deletedDataList.add(del);
        gen.writeObject(deletedDataList);
        String deletedData = gen.getAsString();

        // ＤＢ反映
        OpportunityLineItemBulkEditController.reflectEditedData(opp.Id, draftValues, deletedData, null, 0, false);
    }

    /**
     * ＤＢ反映処理：正常終了の場合（追加商品）
     * 価格表エントリ(商談に紐づく価格表)が未登録
     * 価格表エントリ(標準価格表)が登録済み
     * 
     */
     @isTest(SeeAllData=true)
    static void unitTest_002() {
        Opportunity opp = [select Id from Opportunity limit 1];
        OpportunityLineItem opportunityLineItem = [select Id from OpportunityLineItem limit 1];
        // スタンダードの価格表を指定する必要がある
        Pricebook2 pricebook2Standard = [select Id from Pricebook2 where isStandard = true];
        // 商品登録
        Product2 product2 = new Product2();
        product2.Name = 'Name';
        product2.IsActive = true;
        product2.CountryMode__c = 'J';  // TODO
        product2.Katashiki__c = 'SU8240(Regulus)';  // TODO
        product2.ItemName__c = 'ItemName';
        insert product2;
        PricebookEntry pricebookEntryStandard = new PricebookEntry();
        pricebookEntryStandard.Pricebook2Id = pricebook2Standard.Id;
        pricebookEntryStandard.Product2Id = product2.Id;
        pricebookEntryStandard.UnitPrice = 10000;
        pricebookEntryStandard.IsActive = true;
        // 一旦FORループの中にinsertしますが、後ほど外側に移動する TODO
        insert pricebookEntryStandard;
        
        // draftValues
        JSONGenerator gen = JSON.createGenerator(true);
        List<DraftValues2> draftValuesList = new List<DraftValues2>();
        DraftValues2 d = new DraftValues2();
        d.Id = 'Add' + product2.Id;
        d.Name = 'Name';
        d.Quantity = '1';
        d.UnitPrice = '100.1';
        d.ServiceDate = '';
        d.Description = '';
        draftValuesList.add(d);
        gen.writeObject(draftValuesList);
        String draftValues = gen.getAsString();

        // deletedData
        gen = JSON.createGenerator(true);
        List<DraftValues> deletedDataList = new List<DraftValues>();
        DraftValues del = new DraftValues();
        del.Id = opportunityLineItem.Id;
        deletedDataList.add(del);
        gen.writeObject(deletedDataList);
        String deletedData = gen.getAsString();

        // ＤＢ反映
        OpportunityLineItemBulkEditController.reflectEditedData(opp.Id, draftValues, deletedData, null, 0, false);
    }

    /**
     * ＤＢ反映処理：正常終了の場合（追加商品）
     * 価格表エントリ(商談に紐づく価格表)が登録済み
     * 価格表エントリ(標準価格表)が登録済み
     * 
     */
     @isTest(SeeAllData=true)
    static void unitTest_003() {
        Opportunity opp = [select Id, Pricebook2Id from Opportunity where Pricebook2Id != null limit 1];
        OpportunityLineItem opportunityLineItem = [select Id from OpportunityLineItem limit 1];
        // スタンダードの価格表を指定する必要がある
        Pricebook2 pricebook2Standard = [select Id from Pricebook2 where isStandard = true];
        // 商品登録
        Product2 product2 = new Product2();
        product2.Name = 'Name';
        product2.IsActive = true;
        product2.CountryMode__c = 'J';  // TODO
        product2.Katashiki__c = 'SU8240(Regulus)';  // TODO
        product2.ItemName__c = 'ItemName';
        insert product2;
        PricebookEntry pricebookEntryStandard = new PricebookEntry();
        pricebookEntryStandard.Pricebook2Id = pricebook2Standard.Id;
        pricebookEntryStandard.Product2Id = product2.Id;
        pricebookEntryStandard.UnitPrice = 10000;
        pricebookEntryStandard.IsActive = true;
        insert pricebookEntryStandard;
        PricebookEntry pricebookEntry = new PricebookEntry();
        pricebookEntry.Pricebook2Id = opp.Pricebook2Id;
        pricebookEntry.Product2Id = product2.Id;
        pricebookEntry.UnitPrice = 10001;
        pricebookEntry.IsActive = true;
        insert pricebookEntry;
        
        // draftValues
        JSONGenerator gen = JSON.createGenerator(true);
        List<DraftValues2> draftValuesList = new List<DraftValues2>();
        DraftValues2 d = new DraftValues2();
        d.Id = 'Add' + product2.Id;
        d.Name = 'Name';
        d.Quantity = '1';
        d.UnitPrice = '100.1';
        d.ServiceDate = '';
        d.Description = '';
        draftValuesList.add(d);
        gen.writeObject(draftValuesList);
        String draftValues = gen.getAsString();

        // deletedData
        gen = JSON.createGenerator(true);
        List<DraftValues> deletedDataList = new List<DraftValues>();
        DraftValues del = new DraftValues();
        del.Id = opportunityLineItem.Id;
        deletedDataList.add(del);
        gen.writeObject(deletedDataList);
        String deletedData = gen.getAsString();

        // ＤＢ反映
        OpportunityLineItemBulkEditController.reflectEditedData(opp.Id, draftValues, deletedData, null, 0, false);
    }

    /**
     * ＤＢ反映処理：正常終了の場合（新規商品）
     * 
     */
     @isTest(SeeAllData=true)
    static void unitTest_004() {
        Opportunity opp = [select Id from Opportunity limit 1];
        OpportunityLineItem opportunityLineItem = [select Id from OpportunityLineItem limit 1];
        
        // draftValues
        JSONGenerator gen = JSON.createGenerator(true);
        List<DraftValues> draftValuesList = new List<DraftValues>();
        DraftValues d = new DraftValues();
        d.Id = 'New';
        d.Name = 'Name';
        d.Quantity = 1;
        d.UnitPrice = 100.1;
        d.ServiceDate = '2019-12-05';
        d.Description = 'Description';
        draftValuesList.add(d);
        gen.writeObject(draftValuesList);
        String draftValues = gen.getAsString();

        // deletedData
        gen = JSON.createGenerator(true);
        List<DraftValues> deletedDataList = new List<DraftValues>();
        DraftValues del = new DraftValues();
        del.Id = opportunityLineItem.Id;
        deletedDataList.add(del);
        gen.writeObject(deletedDataList);
        String deletedData = gen.getAsString();

        // ＤＢ反映
        OpportunityLineItemBulkEditController.reflectEditedData(opp.Id, draftValues, deletedData, null, 0, false);
    }

    /**
     * ＤＢ反映処理：正常終了の場合（更新商品）
     * 
     */
     @isTest(SeeAllData=true)
    static void unitTest_005() {
        Opportunity opp = [select Id from Opportunity limit 1];
        OpportunityLineItem opportunityLineItem = [select Id from OpportunityLineItem limit 1];
        
        // draftValues
        JSONGenerator gen = JSON.createGenerator(true);
        List<DraftValues> draftValuesList = new List<DraftValues>();
        DraftValues d = new DraftValues();
        d.Id = opportunityLineItem.Id;
        d.Name = 'Name';
        d.Quantity = 1;
        d.UnitPrice = 100.1;
        d.ServiceDate = '2019-12-05';
        d.Description = 'Description';
        draftValuesList.add(d);
        gen.writeObject(draftValuesList);
        String draftValues = gen.getAsString();

        // deletedData
        gen = JSON.createGenerator(true);
        List<DraftValues> deletedDataList = new List<DraftValues>();
        DraftValues del = new DraftValues();
        del.Id = opportunityLineItem.Id;
        deletedDataList.add(del);
        gen.writeObject(deletedDataList);
        String deletedData = gen.getAsString();

        // ＤＢ反映
        OpportunityLineItemBulkEditController.reflectEditedData(opp.Id, draftValues, deletedData, null, 0, false);
    }
}