force-app/main/default/objects/COWO_CurrencyIsoCode__mdt/COWO_CurrencyIsoCode__mdt.object-meta.xml
<CustomObject>
    <label>通貨コード管理</label>
</CustomObject>

force-app/main/default/objects/COWO_CurrencyIsoCode__mdt/fields/COWO_CurrencyMark__c.field-meta.xml
<CustomField>
    <fullName>COWO_CurrencyMark__c</fullName>
    <label>通貨マーク</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COWO_CurrencyIsoCode__mdt/fields/COWO_Digits__c.field-meta.xml
<CustomField>
    <fullName>COWO_Digits__c</fullName>
    <label>小数点桁数</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/COWO_CurrencyIsoCode__mdt/fields/COWO_DigitsInput__c.field-meta.xml
<CustomField>
    <fullName>COWO_DigitsInput__c</fullName>
    <label>小数点表示</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/COWO_CurrencyIsoCode__mdt/fields/COWO_DisplayFormat__c.field-meta.xml
<CustomField>
    <fullName>COWO_DisplayFormat__c</fullName>
    <label>フォーマット</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/SAWO_Currency__c.field-meta.xml
<CustomField>
    <fullName>SAWO_Currency__c</fullName>
    <description>取引先マスタの項目値</description>
    <label>通貨</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/SAWO_DetailCategory__c.field-meta.xml
<CustomField>
    <fullName>SAWO_DetailCategory__c</fullName>
    <description>SAPの明細カテゴリ</description>
    <label>明細カテゴリ（STE)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Z110</fullName>
                <label>Z110:直送</label>
            </value>
            <value>
                <fullName>Z100</fullName>
                <label>Z100:在庫引当</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/SAWO_DetailCategory_MTE__c.field-meta.xml
<CustomField>
    <fullName>SAWO_DetailCategory_MTE__c</fullName>
    <description>S/4の明細カテゴリ</description>
    <label>Item Category (MTE)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CB1</fullName>
                <label>CB1:Drop ship w Not.</label>
            </value>
            <value>
                <fullName>CB2</fullName>
                <label>CB:2:Drop ship w/out Not.</label>
            </value>
            <value>
                <fullName>TAN</fullName>
                <default>true</default>
                <label>TAN:Distribution</label>
            </value>
            <value>
                <fullName>DB1</fullName>
                <label>DB1:Milst請求Pl+3Pw/ASN</label>
            </value>
            <value>
                <fullName>DB2</fullName>
                <label>DB2:Milst請求Pl+3Pw/oASN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/SAWO_MaterialGroup1__c.field-meta.xml
<CustomField>
    <fullName>SAWO_MaterialGroup1__c</fullName>
    <description>S4連携項目</description>
    <label>品目グループ1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E</fullName>
                <label>E:設計手配</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>C:自動手配</label>
            </value>
            <value>
                <fullName>W</fullName>
                <label>W:WBS手配</label>
            </value>
            <value>
                <fullName>Z01</fullName>
                <label>Z01:特殊鋼</label>
            </value>
            <value>
                <fullName>Z02</fullName>
                <label>Z02:普通鋼・非鉄原料・非鉄製品</label>
            </value>
            <value>
                <fullName>Z03</fullName>
                <label>Z03:機能部品・樹脂原料</label>
            </value>
            <value>
                <fullName>Z04</fullName>
                <label>Z04:半導体・液晶・液晶部材</label>
            </value>
            <value>
                <fullName>001</fullName>
                <label>001:電子</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>002:光学</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>003:SEM</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>004:TEM</label>
            </value>
            <value>
                <fullName>005</fullName>
                <label>005:バイオ</label>
            </value>
            <value>
                <fullName>006</fullName>
                <label>006:医用</label>
            </value>
            <value>
                <fullName>007</fullName>
                <label>007:評価新事業</label>
            </value>
            <value>
                <fullName>008</fullName>
                <label>008:ゲート</label>
            </value>
            <value>
                <fullName>009</fullName>
                <label>009:アッシャー</label>
            </value>
            <value>
                <fullName>010</fullName>
                <label>010:プロセス部品</label>
            </value>
            <value>
                <fullName>011</fullName>
                <label>011:プロセス改造</label>
            </value>
            <value>
                <fullName>012</fullName>
                <label>012:分析（HHS）/（HHA）</label>
            </value>
            <value>
                <fullName>013</fullName>
                <label>013:HFS</label>
            </value>
            <value>
                <fullName>014</fullName>
                <label>014:HSL</label>
            </value>
            <value>
                <fullName>015</fullName>
                <label>015:HMS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/SAWO_PlantCode__c.field-meta.xml
<CustomField>
    <fullName>SAWO_PlantCode__c</fullName>
    <description>S4連携用項目</description>
    <label>プラント (STE)</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/SAWO_PlantCode_MTE__c.field-meta.xml
<CustomField>
    <fullName>SAWO_PlantCode_MTE__c</fullName>
    <description>S4連携用項目</description>
    <label>プラント (MTE)</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/SAWO_ProfitCenter__c.field-meta.xml
<CustomField>
    <fullName>SAWO_ProfitCenter__c</fullName>
    <label>利益センタ(STE)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/SAWO_ProfitCenter_MTE__c.field-meta.xml
<CustomField>
    <fullName>SAWO_ProfitCenter_MTE__c</fullName>
    <formula>Opportunity.SAWO_ProfitCenter_MTE__c</formula>
    <label>利益センタ(MTE)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/SAWO_QuantityUnit__c.field-meta.xml
<CustomField>
    <fullName>SAWO_QuantityUnit__c</fullName>
    <description>S4連携項目</description>
    <label>基本数量単位</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MT</fullName>
                <label>MT:後で修正</label>
            </value>
            <value>
                <fullName>CV</fullName>
            </value>
            <value>
                <fullName>PC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/SAWO_Recording_Division__c.field-meta.xml
<CustomField>
    <fullName>SAWO_Recording_Division__c</fullName>
    <description>DX要件で追加</description>
    <label>計上区分</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Z0</fullName>
                <default>true</default>
                <label>Z0:完納</label>
            </value>
            <value>
                <fullName>Z1</fullName>
                <label>Z1:分納</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/SAWO_RejectionReason__c.field-meta.xml
<CustomField>
    <fullName>SAWO_RejectionReason__c</fullName>
    <description>S4連携項目</description>
    <label>拒否理由</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Z1</fullName>
                <label>Z1:キャンセル</label>
            </value>
            <value>
                <fullName>00</fullName>
                <label>00:Assigned by the System (Internal)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/SAWO_SalesUnit__c.field-meta.xml
<CustomField>
    <fullName>SAWO_SalesUnit__c</fullName>
    <label>販売単位</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>%</fullName>
            </value>
            <value>
                <fullName>%O</fullName>
            </value>
            <value>
                <fullName>°F</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>22S</fullName>
            </value>
            <value>
                <fullName>33</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>ACR</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>BAG</fullName>
            </value>
            <value>
                <fullName>BAR</fullName>
            </value>
            <value>
                <fullName>bbl</fullName>
            </value>
            <value>
                <fullName>bft</fullName>
            </value>
            <value>
                <fullName>bgl</fullName>
            </value>
            <value>
                <fullName>BQK</fullName>
            </value>
            <value>
                <fullName>Bqm</fullName>
            </value>
            <value>
                <fullName>bsc</fullName>
            </value>
            <value>
                <fullName>btl</fullName>
            </value>
            <value>
                <fullName>BTU</fullName>
            </value>
            <value>
                <fullName>BYr</fullName>
            </value>
            <value>
                <fullName>C3S</fullName>
            </value>
            <value>
                <fullName>CAN</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CCM</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CD3</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/SAWO_StorageLocation__c.field-meta.xml
<CustomField>
    <fullName>SAWO_StorageLocation__c</fullName>
    <description>S4連携項目　他受注に在庫が引き当てられないよう、受注の時点で指定しておく</description>
    <label>保管場所(STE)</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/SAWO_StorageLocation_MTE__c.field-meta.xml
<CustomField>
    <fullName>SAWO_StorageLocation_MTE__c</fullName>
    <description>S4連携用項目</description>
    <label>保管場所(MTE)</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OLIPickListSupportController.cls
public with sharing class OLIPickListSupportController {
    public OLIPickListSupportController() {}

    /**
     * 画面初期処理
     * @param なし
     * @return 結果
     */
    @AuraEnabled
    public static String init(String opportunityLineItemId,
                              String currencyISOCode,
                              String selectQuantityUnit,
                              String selectDetailCategory,
                              String selectDetailCategoryMTE,
                              String selectRejectionReason,
                              String selectPlantCode,
                              String selectPlantCodeMTE,
                              String selectStorageLocation,
                              String selectStorageLocationMTE,
                              String selectCurrency,
                              String selectRecordingDivision,
                              String selectProfitCenter,
                              String selectProfitCenterMTE,
                              String selectMaterialGroup1,
                              String selectSalesUnit){
        System.debug('init');

        UTL_CO_OvcSapPlant sap = new UTL_CO_OvcSapPlant();
        UTL_CO_OvcSapPlant.UTL_CO_PlantAll res = sap.getOrgInfo('1710', '1000', selectPlantCode);
        System.debug('selectPlantCode' + selectPlantCode);

        // 型式の選択リスト定義を取得する
        List<SerializableSelectOption> quantityUnitOptions = getSalutationPicklist(new SerializableSelectOption('', '--',FALSE), 'OpportunityLineItem', 'SAWO_QuantityUnit__c',selectQuantityUnit);
        List<SerializableSelectOption> detailCategoryOptions = getSalutationPicklist(new SerializableSelectOption('', '--',FALSE), 'OpportunityLineItem', 'SAWO_DetailCategory__c',selectDetailCategory);
        List<SerializableSelectOption> detailCategoryMTEOptions = getSalutationPicklist(new SerializableSelectOption('', '--',FALSE), 'OpportunityLineItem', 'SAWO_DetailCategory_MTE__c',selectDetailCategoryMTE);
        List<SerializableSelectOption> rejectionReasonOptions = getSalutationPicklist(new SerializableSelectOption('', '--',FALSE), 'OpportunityLineItem', 'SAWO_RejectionReason__c',selectRejectionReason);
        List<SerializableSelectOption> plantCodeOptions = getS4SalutationPicklist(new SerializableSelectOption('', '--',FALSE), res, 'plantSTE',selectPlantCode);
        List<SerializableSelectOption> plantCodeMTEOptions = getS4SalutationPicklist(new SerializableSelectOption('', '--',FALSE), res, 'plantMTE',selectPlantCodeMTE);//plantSelectOptions;
        List<SerializableSelectOption> storageLocationOptions = getS4SalutationPicklist(new SerializableSelectOption('', '--',FALSE), res, 'storageLocSTE',selectStorageLocation);//storageLocationOptionSTE;
        List<SerializableSelectOption> storageLocationMTEOptions = getS4SalutationPicklist(new SerializableSelectOption('', '--',FALSE), res, 'storageLocMTE',selectStorageLocationMTE);//storageLocationOptionMTE;
        List<SerializableSelectOption> currencyOptions = getSalutationPicklist(new SerializableSelectOption('', '--',FALSE), 'OpportunityLineItem', 'CurrencyISOCode',selectCurrency);
        List<SerializableSelectOption> recordingDivisionOptions = getSalutationPicklist(new SerializableSelectOption('', '--',FALSE), 'OpportunityLineItem', 'SAWO_Recording_Division__c',selectRecordingDivision);
        List<SerializableSelectOption> profitCenterOptions = getS4SalutationPicklist(new SerializableSelectOption('', '--',FALSE), res, 'profitCenterSTE',selectProfitCenter);//profitCenterOptionSTE;
        List<SerializableSelectOption> profitCenterMTEOptions = getS4SalutationPicklist(new SerializableSelectOption('', '--',FALSE), res, 'profitCenterMTE',selectProfitCenterMTE);//profitCenterOptionMTE;
        List<SerializableSelectOption> materialGroup1Options = getSalutationPicklist(new SerializableSelectOption('', '--',FALSE), 'OpportunityLineItem', 'SAWO_MaterialGroup1__c',selectMaterialGroup1);
        List<SerializableSelectOption> salesUnitOptions = getSalutationPicklist(new SerializableSelectOption('', '--',FALSE), 'OpportunityLineItem', 'SAWO_SalesUnit__c',selectSalesUnit);

        // 画面表示フォーマット
        system.debug('currencyCode ' + CurrencyIsoCode );
        COWO_CurrencyIsoCode__mdt currencymdt = [SELECT Id, DeveloperName, COWO_Digits__c, COWO_CurrencyMark__c, COWO_DisplayFormat__c, COWO_DigitsInput__c FROM COWO_CurrencyIsoCode__mdt where DeveloperName =: CurrencyIsoCode limit 1];
        String format = currencymdt.COWO_DisplayFormat__c;

        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        gen.writeNumberField('returnCode', 0); // 正常終了
        gen.writeObjectField('SAWO_QuantityUnit__c', quantityUnitOptions);
        gen.writeObjectField('SAWO_DetailCategory__c', detailCategoryOptions);
        gen.writeObjectField('SAWO_DetailCategory_MTE__c', detailCategoryMTEOptions);
        gen.writeObjectField('SAWO_RejectionReason__c', rejectionReasonOptions);
        gen.writeObjectField('SAWO_PlantCode__c', plantCodeOptions);
        gen.writeObjectField('SAWO_PlantCode_MTE__c', plantCodeMTEOptions);
        gen.writeObjectField('SAWO_StorageLocation__c', storageLocationOptions);
        gen.writeObjectField('SAWO_StorageLocation_MTE__c', storageLocationMTEOptions);
        gen.writeObjectField('SAWO_Currency__c', currencyOptions);
        gen.writeObjectField('SAWO_Recording_Division__c', recordingDivisionOptions);
        gen.writeObjectField('SAWO_ProfitCenter__c', profitCenterOptions);
        gen.writeObjectField('SAWO_ProfitCenter_MTE__c', profitCenterMTEOptions);
        gen.writeObjectField('SAWO_MaterialGroup1__c', materialGroup1Options);
        gen.writeObjectField('SAWO_SalesUnit__c', salesUnitOptions);
        gen.writeStringField('format', format);
        gen.writeEndObject();
        
        // Get the JSON string.
        String JSONString = gen.getAsString();

        return JSONString;
    }

    /**
     * plantSTE Changeイベント処理
     * @param plantste
     * @return 結果
     */
    @AuraEnabled
    public static String getStorageSTEByPlantste(String plantste){
        System.debug('plantste' + plantste);
        /*UTL_CO_OvcSapPlant sap = new UTL_CO_OvcSapPlant();
        //UTL_CO_OvcSapPlant.UTL_CO_PlantAll res = sap.getOrgInfo('1710', '1000', '1000');
        UTL_CO_OvcSapPlant.UTL_CO_PlantAll res = sap.getOrgInfo('1710', '1000',plantste);
        List<SerializableSelectOption> storageLocationOptions = getS4SalutationPicklist(new SerializableSelectOption('', '--',FALSE), res, 'storageLocSTE','');//storageLocationOptionSTE;
*/
        UTL_CO_OvcSapPlant sap = new UTL_CO_OvcSapPlant();
        UTL_CO_OvcSapPlant.UTL_CO_PlantAll res = sap.getOrgInfo('1710', '1000',plantste);
        List<SerializableSelectOption> storageLocationOptions = getS4SalutationPicklist(new SerializableSelectOption('', '--',FALSE), res, 'storageLocSTE','');//storageLocationOptionSTE;
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        gen.writeNumberField('returnCode', 0); // 正常終了
        gen.writeObjectField('SAWO_StorageLocation__c', storageLocationOptions);
        gen.writeEndObject();

        // Get the JSON string.
        String JSONString = gen.getAsString();

        return JSONString;
        

    }

    public static Map<String, String> picklistValues(String objectName, String fieldName) {
        Map<String, String> values = new Map<String, String>{};

        List<Schema.DescribeSobjectResult> results = Schema.describeSObjects(new List<String>{objectName});

        for(Schema.DescribeSobjectResult res : results) {
            for (Schema.PicklistEntry entry : res.fields.getMap().get(fieldName).getDescribe().getPicklistValues()) {
                if (entry.isActive()) {
                    if(fieldName.equals('CurrencyISOCode')){
                        values.put(entry.getValue(), entry.getValue() +':'+ entry.getLabel());
                    }else {
                        values.put(entry.getValue(), entry.getLabel());
                    }
                }
            }
        }

        return values;
    }

    public static Map<String, String> pickS4listValues(UTL_CO_OvcSapPlant.UTL_CO_PlantAll plantAll,String fieldName) {
        Map<String, String> values = new Map<String, String>{};

        List<UTL_CO_OvcSapPlant.UTL_CO_Plant> plantList = plantAll.plantMte;
        List<UTL_CO_OvcSapPlant.UTL_CO_StorageLocation> storageLocSteList = plantAll.storageLocSte;
        List<UTL_CO_OvcSapPlant.UTL_CO_ProfitCenter> profitCenterMTEList = plantAll.profitCenterMte;
        List<UTL_CO_OvcSapPlant.UTL_CO_ProfitCenter> profitCenterSTEList = plantAll.profitCenterSte;
        List<UTL_CO_OvcSapPlant.UTL_CO_StorageLocation> storageLocationList = new List<UTL_CO_OvcSapPlant.UTL_CO_StorageLocation>();
        if(fieldName.equals('plantMTE')){
            for(UTL_CO_OvcSapPlant.UTL_CO_Plant plant : plantList){
                values.put(plant.code, plant.code + ':' + plant.text);
            }
        }else if(fieldName.equals('plantSTE')){
            values.put('1000', '1000:日立ハイテク（本社）');
            values.put('1010', '1010:日立ハイテク（那珂）');
            values.put('1020', '1020:日立ハイテク（笠戸）');
            values.put('1030', '1030:日立ハイテク（大牟田）');
        }else if(fieldName.equals('storageLocMTE')){
            storageLocationList = plantList[0].storageLocations;
            for(UTL_CO_OvcSapPlant.UTL_CO_StorageLocation storageLocation : storageLocationList){
                values.put(storageLocation.code,storageLocation.code  + ':' + storageLocation.text);
            }
        }else if(fieldName.equals('storageLocSTE')){
            for(UTL_CO_OvcSapPlant.UTL_CO_StorageLocation storageLocationSTE : storageLocSteList){
                values.put(storageLocationSTE.code,storageLocationSTE.code  + ':' + storageLocationSTE.text);
            }
        }
        else if(fieldName.equals('profitCenterMTE')){
            for(UTL_CO_OvcSapPlant.UTL_CO_ProfitCenter profitCenterMTE : profitCenterMTEList){
                values.put(profitCenterMTE.code,profitCenterMTE.code  + ':' + profitCenterMTE.text);
            }
        }else if(fieldName.equals('profitCenterSTE')){
            for(UTL_CO_OvcSapPlant.UTL_CO_ProfitCenter profitCenterSTE : profitCenterSTEList){
                values.put(profitCenterSTE.code,profitCenterSTE.code  + ':' + profitCenterSTE.text);
            }
        }
        return values;
    }

    public static List<SerializableSelectOption> getSalutationPicklist(SerializableSelectOption selectOption, String objectName, String fieldName,String selectValue) {
        List<SerializableSelectOption> selectOptions = new List<SerializableSelectOption>();
        if(selectOption != null){
            selectOptions.add(selectOption);
        }
        Map<String, String> salutationValueLabels = picklistValues(objectName, fieldName);
        for (String value : salutationValueLabels.keySet()) {
            Boolean selected = false;
            if(selectValue != null && value.equals(selectValue)){
                selected = true;
            }
            selectOptions.add(new SerializableSelectOption(value, salutationValueLabels.get(value),selected));
        }

        return selectOptions;
    }

    public static List<SerializableSelectOption> getS4SalutationPicklist(SerializableSelectOption selectOption, UTL_CO_OvcSapPlant.UTL_CO_PlantAll plantAll,String fieldName,String selectValue) {
        List<SerializableSelectOption> selectOptions = new List<SerializableSelectOption>();
        if(selectOption != null){
            selectOptions.add(selectOption);
        }
        Map<String, String> salutationValueLabels = pickS4listValues(plantAll,fieldName);
        for (String value : salutationValueLabels.keySet()) {
            Boolean selected = false;
            if(selectValue != null && value.equals(selectValue)){
                selected = true;
            }
            selectOptions.add(new SerializableSelectOption(value, salutationValueLabels.get(value),selected));
        }
        return selectOptions;
    }
    
    public class SerializableSelectOption {

        public String label {get; set;}
        public String value {get; set;}
        public Boolean selected{get; set;}

        public SerializableSelectOption(SelectOption so) {
            this.label = so.getLabel();
            this.value = so.getValue();
            this.selected = false;
        }

        public SerializableSelectOption(PicklistEntry pe) {
            this.label = pe.getLabel();
            this.value = pe.getValue();
            this.selected = false;
        }

        public SerializableSelectOption(String label, String value,Boolean selected) {
            this.label = label;
            this.value = value;
            this.selected = selected;
        }
    }
}